services:
  yarn:
    image: 'nextjs:latest'
    init: true
    entrypoint: yarn
    user: node
    volumes:
      - .:/app
      - yarn_cache:/node/.cache/yarn/v1
    networks:
      - app_network

volumes:
  yarn_cache:
  data:
  mysql-data:
    driver: local

networks:
  app_network:
    driver: bridge
