import { EmployeesTestCase } from "./EmployeesTestCase";

const employeeTestCase = new EmployeesTestCase();

export const dataProvider = {
  invalidRequest: employeeTestCase.create("emptyParams"),
  emptyNumberEmployee: employeeTestCase.create("emptyNumberEmployee"),
  emptyName: employeeTestCase.create("emptyName"),
  emptyPaternalLastName: employeeTestCase.create("emptyPaternalLastName"),
  emptyMaternalLastName: employeeTestCase.create("emptyMaternalLastName"),
  emptyBirthday: employeeTestCase.create("emptyBirthday"),
  emptyGenderId: employeeTestCase.create("emptyGenderId"),
  emptyRfc: employeeTestCase.create("emptyRfc"),
  emptyCurp: employeeTestCase.create("emptyCurp"),
  longNumberEmployee: employeeTestCase.create("longNumberEmployee"),
  longName: employeeTestCase.create("longName"),
  longPaternalLastName: employeeTestCase.create("longPaternalLastName"),
  longMaternalLastName: employeeTestCase.create("longMaternalLastName"),
  emptyAddressLine1: employeeTestCase.create("emptyAddressLine1"),
  longAddressLine1: employeeTestCase.create("longAddressLine1"),
  emptyAddressLine2: employeeTestCase.create("emptyAddressLine2"),
  longAddressLine2: employeeTestCase.create("longAddressLine2"),
  emptyAddressLine4: employeeTestCase.create("emptyAddressLine4"),
  longAddressLine4: employeeTestCase.create("longAddressLine4"),
  emptyPostalCode: employeeTestCase.create("emptyPostalCode"),
  emptyPostalCodeSat: employeeTestCase.create("emptyPostalCodeSat"),
  emptyMunicipalityId: employeeTestCase.create("emptyMunicipalityId"),
  duplicatedRfcCurp: employeeTestCase.create("duplicatedRfcCurp"),
  emptyStartJobDate: employeeTestCase.create("emptyStartJobDate"),
  emptyEndJobDate: employeeTestCase.create("emptyEndJobDate"),
  emptyCategoryId: employeeTestCase.create("emptyCategoryId"),
  emptyEmployeeTypeName: employeeTestCase.create("emptyEmployeeTypeName"),
  invalidEmployeeTypeName: employeeTestCase.create("invalidEmployeeTypeName"),
  emptyEmployeeTypeBaseSindicalizado: employeeTestCase.create("emptyEmployeeTypeBaseSindicalizado"),
  emptyDireccionId: employeeTestCase.create("emptyDireccionId"),
  validData: employeeTestCase.create("validData", 200),
};
