import { createTestCase } from "../../../common/utils";

export const dataProvider = {
  invalidRequest: createTestCase("emptyParams"),
  emptyNumberEmployee: createTestCase("emptyNumberEmployee"),
  emptyName: createTestCase("emptyName"),
  emptyPaternalLastName: createTestCase("emptyPaternalLastName"),
  emptyMaternalLastName: createTestCase("emptyMaternalLastName"),
  emptyBirthday: createTestCase("emptyBirthday"),
  emptyGenderId: createTestCase("emptyGenderId"),
  emptyRfc: createTestCase("emptyRfc"),
  emptyCurp: createTestCase("emptyCurp"),
  longNumberEmployee: createTestCase("longNumberEmployee"),
  longName: createTestCase("longName"),
  longPaternalLastName: createTestCase("longPaternalLastName"),
  longMaternalLastName: createTestCase("longMaternalLastName"),
  emptyAddressLine1: createTestCase("emptyAddressLine1"),
  longAddressLine1: createTestCase("longAddressLine1"),
  emptyAddressLine2: createTestCase("emptyAddressLine2"),
  longAddressLine2: createTestCase("longAddressLine2"),
  emptyAddressLine4: createTestCase("emptyAddressLine4"),
  longAddressLine4: createTestCase("longAddressLine4"),
  emptyPostalCode: createTestCase("emptyPostalCode"),
  emptyPostalCodeSat: createTestCase("emptyPostalCodeSat"),
  emptyMunicipalityId: createTestCase("emptyMunicipalityId"),
  duplicatedRfcCurp: createTestCase("duplicatedRfcCurp"),
  emptyStartJobDate: createTestCase("emptyStartJobDate"),
  emptyEndJobDate: createTestCase("emptyEndJobDate"),
  emptyCategoryId: createTestCase("emptyCategoryId"),
  emptyEmployeeTypeName: createTestCase("emptyEmployeeTypeName"),
  invalidEmployeeTypeName: createTestCase("invalidEmployeeTypeName"),
  emptyEmployeeTypeBaseSindicalizado: createTestCase("emptyEmployeeTypeBaseSindicalizado"),
  emptyDireccionId: createTestCase("emptyDireccionId"),
  validData: createTestCase("validData", 200),
};
