import { generator } from "./generator";
import { EmployeeTypeName } from "@/common/constants/EmployeeType";

export const request = {
  emptyParams: {},
  emptyNumberEmployee: generator.request({ numberEmployee: "" }),
  emptyName: generator.request({ name: "" }),
  emptyPaternalLastName: generator.request({ paternalLastName: "" }),
  emptyMaternalLastName: generator.request({ maternalLastName: "" }),
  emptyBirthday: generator.request({ birthday: "" }),
  emptyGenderId: generator.request({ genderId: "0" }),
  emptyRfc: generator.request({ rfc: "" }),
  emptyCurp: generator.request({ curp: "" }),
  longNumberEmployee: generator.request({ numberEmployee: "1001931" }),
  longName: generator.request({ name: "a".repeat(256) }),
  longPaternalLastName: generator.request({ paternalLastName: "a".repeat(256) }),
  longMaternalLastName: generator.request({ maternalLastName: "a".repeat(256) }),
  duplicatedRfcCurp: generator.request({}),
  validData: generator.request({}),
  emptyAddressLine1: generator.request({ addressLine1: "" }),
  longAddressLine1: generator.request({ addressLine1: "a".repeat(256) }),
  emptyAddressLine2: generator.request({ addressLine2: "" }),
  longAddressLine2: generator.request({ addressLine2: "a".repeat(256) }),
  emptyAddressLine4: generator.request({ addressLine4: "" }),
  longAddressLine4: generator.request({ addressLine4: "a".repeat(256) }),
  emptyPostalCode: generator.request({ postalCode: "" }),
  emptyPostalCodeSat: generator.request({ postalCodeSat: "" }),
  emptyMunicipalityId: generator.request({ municipalityId: "0" }),
  emptyStartJobDate: generator.request({ startJobDate: "" }),
  emptyEndJobDate: generator.request({ endJobDate: "" }),
  emptyCategoryId: generator.request({ categoryId: "0" }),
  emptyEmployeeTypeName: generator.request({ employeeTypeName: "" }),
  invalidEmployeeTypeName: generator.request({ employeeTypeName: "base" }),
  emptyEmployeeTypeBaseSindicalizado: generator.request({
    employeeTypeName: EmployeeTypeName.BASE_SINDICALIZADO,
  }),
  emptyDireccionId: generator.request({ direccionId: "0" }),
};
