import { IEmployee } from "@/app/api/employees/interface";
import { dataProvider } from "./dataProvider";

export const testCases = [
  {
    description: "should return invalid request",
    requestData: {} as IEmployee,
    expectedStatus: dataProvider.invalidRequest.status,
    expectedResponse: dataProvider.invalidRequest.response,
  },
  {
    description: "should return error for empty number employee",
    requestData: dataProvider.emptyNumberEmployee.request as IEmployee,
    expectedStatus: dataProvider.emptyNumberEmployee.status,
    expectedResponse: dataProvider.emptyNumberEmployee.response,
  },
  {
    description: "should return error for empty name",
    requestData: dataProvider.emptyName.request as IEmployee,
    expectedStatus: dataProvider.emptyName.status,
    expectedResponse: dataProvider.emptyName.response,
  },
  {
    description: "should return error for empty paternal last name",
    requestData: dataProvider.emptyPaternalLastName.request as IEmployee,
    expectedStatus: dataProvider.emptyPaternalLastName.status,
    expectedResponse: dataProvider.emptyPaternalLastName.response,
  },
  {
    description: "should return error for empty maternal last name",
    requestData: dataProvider.emptyMaternalLastName.request as IEmployee,
    expectedStatus: dataProvider.emptyMaternalLastName.status,
    expectedResponse: dataProvider.emptyMaternalLastName.response,
  },
  {
    description: "should return error for empty birthday",
    requestData: dataProvider.emptyBirthday.request as IEmployee,
    expectedStatus: dataProvider.emptyBirthday.status,
    expectedResponse: dataProvider.emptyBirthday.response,
  },
  {
    description: "should return error for empty gender id",
    requestData: dataProvider.emptyGenderId.request as IEmployee,
    expectedStatus: dataProvider.emptyGenderId.status,
    expectedResponse: dataProvider.emptyGenderId.response,
  },
  {
    description: "should return error for empty rfc",
    requestData: dataProvider.emptyRfc.request as IEmployee,
    expectedStatus: dataProvider.emptyRfc.status,
    expectedResponse: dataProvider.emptyRfc.response,
  },
  {
    description: "should return error for empty curp",
    requestData: dataProvider.emptyCurp.request as IEmployee,
    expectedStatus: dataProvider.emptyCurp.status,
    expectedResponse: dataProvider.emptyCurp.response,
  },
  {
    description: "should return error for long number employee",
    requestData: dataProvider.longNumberEmployee.request as IEmployee,
    expectedStatus: dataProvider.longNumberEmployee.status,
    expectedResponse: dataProvider.longNumberEmployee.response,
  },
  {
    description: "should return error for long name",
    requestData: dataProvider.longName.request as IEmployee,
    expectedStatus: dataProvider.longName.status,
    expectedResponse: dataProvider.longName.response,
  },
  {
    description: "should return error for long paternal last name",
    requestData: dataProvider.longPaternalLastName.request as IEmployee,
    expectedStatus: dataProvider.longPaternalLastName.status,
    expectedResponse: dataProvider.longPaternalLastName.response,
  },
  {
    description: "should return error for long maternal last name",
    requestData: dataProvider.longMaternalLastName.request as IEmployee,
    expectedStatus: dataProvider.longMaternalLastName.status,
    expectedResponse: dataProvider.longMaternalLastName.response,
  },
  {
    description: "should return error for existing employee by RFC or CURP",
    requestData: dataProvider.duplicatedRfcCurp.request as IEmployee,
    expectedStatus: dataProvider.duplicatedRfcCurp.status,
    expectedResponse: dataProvider.duplicatedRfcCurp.response,
  },
  {
    description: "should successfully send message with valid data",
    requestData: dataProvider.validData.request as IEmployee,
    expectedStatus: dataProvider.validData.status,
    expectedResponse: dataProvider.validData.response,
  },
  {
    description: "should return error for empty address line 1",
    requestData: dataProvider.emptyAddressLine1.request as IEmployee,
    expectedStatus: dataProvider.emptyAddressLine1.status,
    expectedResponse: dataProvider.emptyAddressLine1.response,
  },
  {
    description: "should return error for long address line 1",
    requestData: dataProvider.longAddressLine1.request as IEmployee,
    expectedStatus: dataProvider.longAddressLine1.status,
    expectedResponse: dataProvider.longAddressLine1.response,
  },
  {
    description: "should return error for empty address line 2",
    requestData: dataProvider.emptyAddressLine2.request as IEmployee,
    expectedStatus: dataProvider.emptyAddressLine2.status,
    expectedResponse: dataProvider.emptyAddressLine2.response,
  },
  {
    description: "should return error for long address line 2",
    requestData: dataProvider.longAddressLine2.request as IEmployee,
    expectedStatus: dataProvider.longAddressLine2.status,
    expectedResponse: dataProvider.longAddressLine2.response,
  },
  {
    description: "should return error for empty address line 4",
    requestData: dataProvider.emptyAddressLine4.request as IEmployee,
    expectedStatus: dataProvider.emptyAddressLine4.status,
    expectedResponse: dataProvider.emptyAddressLine4.response,
  },
  {
    description: "should return error for long address line 4",
    requestData: dataProvider.longAddressLine4.request as IEmployee,
    expectedStatus: dataProvider.longAddressLine4.status,
    expectedResponse: dataProvider.longAddressLine4.response,
  },
  {
    description: "should return error for empty postal code",
    requestData: dataProvider.emptyPostalCode.request as IEmployee,
    expectedStatus: dataProvider.emptyPostalCode.status,
    expectedResponse: dataProvider.emptyPostalCode.response,
  },
  {
    description: "should return error for empty postal code sat",
    requestData: dataProvider.emptyPostalCodeSat.request as IEmployee,
    expectedStatus: dataProvider.emptyPostalCodeSat.status,
    expectedResponse: dataProvider.emptyPostalCodeSat.response,
  },
  {
    description: "should return error for empty municipality Id",
    requestData: dataProvider.emptyMunicipalityId.request as IEmployee,
    expectedStatus: dataProvider.emptyMunicipalityId.status,
    expectedResponse: dataProvider.emptyMunicipalityId.response,
  },
  {
    description: "should return error for empty start job date",
    requestData: dataProvider.emptyStartJobDate.request as IEmployee,
    expectedStatus: dataProvider.emptyStartJobDate.status,
    expectedResponse: dataProvider.emptyStartJobDate.response,
  },
  {
    description: "should return error for empty end job date",
    requestData: dataProvider.emptyEndJobDate.request as IEmployee,
    expectedStatus: dataProvider.emptyEndJobDate.status,
    expectedResponse: dataProvider.emptyEndJobDate.response,
  },
  {
    description: "should return error for empty category id",
    requestData: dataProvider.emptyCategoryId.request as IEmployee,
    expectedStatus: dataProvider.emptyCategoryId.status,
    expectedResponse: dataProvider.emptyCategoryId.response,
  },
  {
    description: "should return error for empty employee type id",
    requestData: dataProvider.emptyEmployeeTypeName.request as IEmployee,
    expectedStatus: dataProvider.emptyEmployeeTypeName.status,
    expectedResponse: dataProvider.emptyEmployeeTypeName.response,
  },
  {
    description: "should return error for invalid employee type name",
    requestData: dataProvider.invalidEmployeeTypeName.request as IEmployee,
    expectedStatus: dataProvider.invalidEmployeeTypeName.status,
    expectedResponse: dataProvider.invalidEmployeeTypeName.response,
  },
  {
    description: "should return error for empty employee type 'base_sindicalizado'",
    requestData: dataProvider.emptyEmployeeTypeBaseSindicalizado.request as IEmployee,
    expectedStatus: dataProvider.emptyEmployeeTypeBaseSindicalizado.status,
    expectedResponse: dataProvider.emptyEmployeeTypeBaseSindicalizado.response,
  },
  {
    description: "should return error for empty direccion id",
    requestData: dataProvider.emptyDireccionId.request as IEmployee,
    expectedStatus: dataProvider.emptyDireccionId.status,
    expectedResponse: dataProvider.emptyDireccionId.response,
  },
];
