const direccion = [
  {
    id: 1,
    name: "coordinacion_asesores",
    display_name: "COORDINACIÓN DE ASESORES",
    secretaria_id: 5,
    active: true,
  },
  {
    id: 2,
    name: "coordinacion_interinstitucional",
    display_name: "COORDINACIÓN DE RELACIONES INTERINSTITUCIONAL",
    secretaria_id: 5,
    active: true,
  },
  {
    id: 3,
    name: "secretaria_particular_despacho_presidente",
    display_name: "SECRETARÍA PARTICULAR DEL DESPACHO DEL PRESIDENTE",
    secretaria_id: 5,
    active: true,
  },
  {
    id: 4,
    name: "presidencia_municipal",
    display_name: "PRESIDENCIA MUNICIPAL",
    secretaria_id: 5,
    active: true,
  },
  {
    id: 5,
    name: "sindicatura",
    display_name: "SINDICATURA",
    secretaria_id: 16,
    active: true,
  },
  {
    id: 6,
    name: "direccion_auditorias_fondos_aportaciones_federales_estatales_municipales",
    display_name: "DIRECCIÓN DE AUDITORÍAS A FONDS DE APORTACIONES FEDERALES ESTATALES Y MUNICIPALES",
    secretaria_id: 1,
    active: true,
  },
  {
    id: 7,
    name: "direccion_auditorias_administrativas_financieras",
    display_name: "DIRECCIÓN DE AUDITORÍAS ADMINISTRATIVAS Y FINANCIERAS",
    secretaria_id: 1,
    active: true,
  },
  {
    id: 8,
    name: "direccion_verificacion_auditoria_obra_publica",
    display_name: "DIRECCIÓN DE VERIFICACIÓN Y AUDITORÍA A LA OBRA PÚBLICA",
    secretaria_id: 1,
    active: true,
  },
  {
    id: 9,
    name: "direccion_investigacion_faltas_administrativas_evolucion_patrimonial",
    display_name: "DIRECCIÓN DE INVESTIGACIÓN DE FALTAS ADMINISTRATIVAS Y EVOLUCIÓN PATRIMONIAL",
    secretaria_id: 1,
    active: true,
  },
  {
    id: 10,
    name: "contraloria_municipal",
    display_name: "CONTRALORÍA MUNICIPAL",
    secretaria_id: 1,
    active: true,
  },
  {
    id: 11,
    name: "coordinacion_general_gabinete_atencion_ciudadana",
    display_name: "COORDINACIÓN GENERAL DE GABINETE Y ATENCION CIUDADANA",
    secretaria_id: 5,
    active: true,
  },
  {
    id: 12,
    name: "direccion_gobierno",
    display_name: "DIRECCIÓN DE GOBIERNO",
    secretaria_id: 14,
    active: true,
  },
  {
    id: 13,
    name: "direccion_tenencia_tierra",
    display_name: "DIRECCIÓN DE TENENCIA DE LA TIERRA",
    secretaria_id: 14,
    active: true,
  },
  {
    id: 14,
    name: "direccion_del_ayuntamiento",
    display_name: "DIRECCIÓN DEL AYUNTAMIENTO",
    secretaria_id: 14,
    active: true,
  },
  {
    id: 15,
    name: "consejeria_juridica",
    display_name: "CONSEJERÍA JURÍDICA",
    secretaria_id: 5,
    active: true,
  },
  {
    id: 16,
    name: "secretaria_general_ayuntamiento",
    display_name: "SECRETARÍA GENERAL DEL AYUNTAMIENTO",
    secretaria_id: 14,
    active: true,
  },
  {
    id: 17,
    name: "coordinacion_general_transparencia",
    display_name: "COORDINACIÓN GENERAL DE LA UNIDAD DE TRANSPARENCIA",
    secretaria_id: 5,
    active: true,
  },
  {
    id: 18,
    name: "coordinacion_tecnologias_informacion_comunicaciones",
    display_name: "COORDINACIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIONES",
    secretaria_id: 5,
    active: true,
  },
  {
    id: 19,
    name: "coordinacion_prevencion_delito",
    display_name: "COORDINACIÓN DE PREVENCIÓN DEL DELITO",
    secretaria_id: 12,
    active: true,
  },
  {
    id: 20,
    name: "direccion_seguridad_publica",
    display_name: "DIRECCIÓN DE SEGURIDAD PÚBLICA",
    secretaria_id: 12,
    active: true,
  },
  {
    id: 21,
    name: "direccion_transito",
    display_name: "DIRECCIÓN DE TRÁNSITO",
    secretaria_id: 12,
    active: true,
  },
  {
    id: 22,
    name: "direccion_transporte",
    display_name: "DIRECCIÓN DE TRANSPORTE",
    secretaria_id: 12,
    active: true,
  },
  {
    id: 23,
    name: "secretaria_seguridad_publica_trasnsito_municipal",
    display_name: "SECRETARÍA DE SEGURIDAD PÚBLICA Y TRÁNSITO MUNICIPAL",
    secretaria_id: 12,
    active: true,
  },
  {
    id: 24,
    name: "direccion_geografia_estadistica",
    display_name: "DIRECCIÓN DE GEOGRAFÍA Y ESTADÍSTICA",
    secretaria_id: 10,
    active: true,
  },
  {
    id: 25,
    name: "direccion_planeacion_estrategica",
    display_name: "DIRECCIÓN DE PLANEACIÓN ESTRATÉGICA",
    secretaria_id: 10,
    active: true,
  },
  {
    id: 26,
    name: "direccion_seguimiento_evaluacion",
    display_name: "DIRECCIÓN DE SEGUIMIENTO Y EVALUACIÓN",
    secretaria_id: 10,
    active: true,
  },
  {
    id: 27,
    name: "direccion_participacion_ciudadana",
    display_name: "DIRECCIÓN DE PARTICIPACIÓN CIUDADANA",
    secretaria_id: 8,
    active: true,
  },
  {
    id: 28,
    name: "secretaria_planeacion",
    display_name: "SECRETARÍA DE PLANEACIÓN",
    secretaria_id: 10,
    active: true,
  },
  {
    id: 29,
    name: "direccion_desarrollo_bienestar_social",
    display_name: "DIRECCIÓN PARA EL DESARROLLO DEL BIENESTAR SOCIAL",
    secretaria_id: 8,
    active: true,
  },
  {
    id: 30,
    name: "direccion_economia_social_solidaria",
    display_name: "DIRECCIÓN DE ECONOMÍA SOCIAL Y SOLIDARIA",
    secretaria_id: 7,
    active: true,
  },
  {
    id: 31,
    name: "direccion_servicios_educativos",
    display_name: "DIRECCIÓN DE SERVICIOS EDUCATIVOS",
    secretaria_id: 8,
    active: true,
  },
  {
    id: 32,
    name: "secretaria_desarrollo_social_educacion",
    display_name: "SECRETARÍA DE DESARROLLO SOCIAL Y EDUCACIÓN",
    secretaria_id: 8,
    active: true,
  },
  {
    id: 33,
    name: "buro_turismo_municipal",
    display_name: "BURÓ DE TURISMO MUNICIPAL",
    secretaria_id: 7,
    active: true,
  },
  {
    id: 34,
    name: "direccion_fomento_economico",
    display_name: "DIRECCIÓN DE FOMENTO ECONÓMICO",
    secretaria_id: 7,
    active: true,
  },
  {
    id: 35,
    name: "secretaria_economia",
    display_name: "SECRETARÍA DE ECONOMÍA",
    secretaria_id: 7,
    active: true,
  },
  {
    id: 36,
    name: "direccion_costos_concursos",
    display_name: "DIRECCIÓN DE COSTOS Y CONCURSOS",
    secretaria_id: 9,
    active: true,
  },
  {
    id: 37,
    name: "direccion_infraestructura",
    display_name: "DIRECCIÓN DE INFRAESTRUCTURA",
    secretaria_id: 9,
    active: true,
  },
  {
    id: 38,
    name: "direccion_proyectos",
    display_name: "DIRECCIÓN DE PROYECTOS",
    secretaria_id: 9,
    active: true,
  },
  {
    id: 39,
    name: "secretaria_ obras_publicas",
    display_name: "SECRETARÍA DE OBRAS PÚBLICAS",
    secretaria_id: 9,
    active: true,
  },
  {
    id: 40,
    name: "clinica_diagnostico_mujer_orientes",
    display_name: "CLÍNICA DE DIAGNÓSTICO DE LA MUJER ORIENTES",
    secretaria_id: 11,
    active: true,
  },
  {
    id: 41,
    name: "direccion_proteccion_riesgos_sanitarios",
    display_name: "DIRECCIÓN DE PROTECCIÓN CONTRA RIESGOS SANITARIOS",
    secretaria_id: 11,
    active: true,
  },
  {
    id: 42,
    name: "direccion_servicios_medicos",
    display_name: "DIRECCIÓN DE SERVICIOS MÉDICOS",
    secretaria_id: 11,
    active: true,
  },
  {
    id: 43,
    name: "direccion_verificaciones_clausuras",
    display_name: "DIRECCIÓN DE VERIFICACIONES Y CLAUSSURAS",
    secretaria_id: 11,
    active: true,
  },
  {
    id: 44,
    name: "secretaria_salud",
    display_name: "SECRETARÍA DE SALUD",
    secretaria_id: 11,
    active: true,
  },
  {
    id: 45,
    name: "direccion_adquisiciones",
    display_name: "DIRECCIÓN DE ADQUISICIONES",
    secretaria_id: 6,
    active: true,
  },
  {
    id: 46,
    name: "direccion_recursos_humanos",
    display_name: "DIRECCIÓN DE RECURSOS HUMANOS",
    secretaria_id: 6,
    active: true,
  },
  {
    id: 47,
    name: "direccion_recursos_materiales",
    display_name: "DIRECCIÓN DE RECURSOS MATERIALES, SERVICIOS GENERALES Y PATRIMONIO MUNICIPAL",
    secretaria_id: 6,
    active: true,
  },
  {
    id: 48,
    name: "oficialia_mayor",
    display_name: "OFICIALIA MAYOR",
    secretaria_id: 6,
    active: true,
  },
  {
    id: 49,
    name: "direccion_alumbrado_publico",
    display_name: "DIRECCIÓN DE ALUMBRADO PÚBLICO",
    secretaria_id: 13,
    active: true,
  },
  {
    id: 50,
    name: "direccion_imagen_urbana_y_areas_verdes",
    display_name: "DIRECCIÓN DE IMAGEN URBANA Y ÁREAS VERDES",
    secretaria_id: 13,
    active: true,
  },
  {
    id: 51,
    name: "direccion_imagen_urbana",
    display_name: "DIRECCIÓN DE IMAGEN URBANA",
    secretaria_id: 13,
    active: true,
  },
  {
    id: 52,
    name: "direccion_limpia_y_aseo_publico",
    display_name: "DIRECCIÓN DE LIMPIA Y ASEO PÚBLICO",
    secretaria_id: 13,
    active: true,
  },
  {
    id: 53,
    name: "direccion_mercados_y_panteones",
    display_name: "DIRECCIÓN DE MERCADOS Y PANTEONES",
    secretaria_id: 13,
    active: true,
  },
  {
    id: 54,
    name: "direccion_obras_viales",
    display_name: "DIRECCIÓN DE OBRAS VIALES",
    secretaria_id: 9,
    active: true,
  },
  {
    id: 55,
    name: "secretaria_servicios_municipales",
    display_name: "SECRETARÍA DE SERVICIOS MUNICIPALES",
    secretaria_id: 13,
    active: true,
  },
];

module.exports = direccion;
