const direccion = [
  {
    id: 1,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_de_asesores",
    display_name: "COORDINACIÓN DE ASESORES",
  },
  {
    id: 2,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_de_relaciones_interinstitucional",
    display_name: "COORDINACIÓN DE RELACIONES INTERINSTITUCIONAL",
  },
  {
    id: 3,
    secretaria_id: 5,
    active: true,
    name: "secretaria_particular_de_despacho_del_presidente",
    display_name: "SECRETARÍA PARTICULAR DE DESPACHO DEL PRESIDENTE",
  },
  {
    id: 4,
    secretaria_id: 5,
    active: true,
    name: "presidencia",
    display_name: "PRESIDENCIA",
  },
  {
    id: 5,
    secretaria_id: 15,
    active: true,
    name: "sindicatura",
    display_name: "SINDICATURA",
  },
  {
    id: 6,
    secretaria_id: 1,
    active: true,
    name: "dir_de_auditorias_a_f_de_aportaciones_fed_est_y_mpales",
    display_name: "DIR. DE AUDITORIAS A F. DE APORTACIONES FED., EST. Y MPALES.",
  },
  {
    id: 7,
    secretaria_id: 1,
    active: true,
    name: "direccion_de_auditorias_administrativas_y_financieras",
    display_name: "DIRECCIÓN DE AUDITORÍAS ADMINISTRATIVAS Y FINANCIERAS",
  },
  {
    id: 8,
    secretaria_id: 1,
    active: true,
    name: "direccion_de_verificacion_y_auditoria_a_la_obra_publica",
    display_name: "DIRECCIÓN DE VERIFICACIÓN Y AUDITORÍA A LA OBRA PÚBLICA",
  },
  {
    id: 9,
    secretaria_id: 1,
    active: true,
    name: "direccion_de_investigacion_de_faltas_administrativas_y_evolucion",
    display_name: "DIRECCIÓN DE INVESTIGACION DE FALTAS ADMINISTRATIVAS Y EVOLUCION",
  },
  {
    id: 10,
    secretaria_id: 1,
    active: true,
    name: "contraloria_municipal",
    display_name: "CONTRALORÍA MUNICIPAL",
  },
  {
    id: 11,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_general_de_gabinete_y_atencion_ciudadana",
    display_name: "COORDINACIÓN GENERAL DE GABINETE Y ATENCION CIUDADANA",
  },
  {
    id: 12,
    secretaria_id: 14,
    active: true,
    name: "direccion_de_gobierno_municipal",
    display_name: "DIRECCIÓN DE GOBIERNO MUNICIPAL",
  },
  {
    id: 13,
    secretaria_id: 14,
    active: true,
    name: "direccion_de_tenencia_de_la_tierra",
    display_name: "DIRECCIÓN DE TENENCIA DE LA TIERRA",
  },
  {
    id: 14,
    secretaria_id: 14,
    active: true,
    name: "direccion_del_ayuntamiento",
    display_name: "DIRECCIÓN DEL AYUNTAMIENTO",
  },
  {
    id: 15,
    secretaria_id: 5,
    active: true,
    name: "consejeria_juridica",
    display_name: "CONSEJERÍA JURÍDICA",
  },
  {
    id: 16,
    secretaria_id: 14,
    active: true,
    name: "secretaria_general_del_ayuntamiento",
    display_name: "SECRETARÍA GENERAL DEL AYUNTAMIENTO",
  },
  {
    id: 17,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_general_de_la_unidad_de_transparencia",
    display_name: "COORDINACIÓN GENERAL DE LA UNIDAD DE TRANSPARENCIA",
  },
  {
    id: 18,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_de_tecnologias_de_la_informacion_y_comunicaciones",
    display_name: "COORDINACIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIÓNES",
  },
  {
    id: 19,
    secretaria_id: 12,
    active: true,
    name: "coordinacion_de_prevencion_del_delito",
    display_name: "COORDINACIÓN DE PREVENCIÓN DEL DELITO",
  },
  {
    id: 20,
    secretaria_id: 12,
    active: true,
    name: "direccion_de_seguridad_publica",
    display_name: "DIRECCIÓN DE SEGURIDAD PÚBLICA",
  },
  {
    id: 21,
    secretaria_id: 12,
    active: true,
    name: "direccion_de_transito",
    display_name: "DIRECCIÓN DE TRÁNSITO",
  },
  {
    id: 22,
    secretaria_id: 12,
    active: true,
    name: "direccion_de_transporte",
    display_name: "DIRECCIÓN DE TRANSPORTE",
  },
  {
    id: 23,
    secretaria_id: 12,
    active: true,
    name: "secretaria_de_seguridad_publica_y_transito_municipal",
    display_name: "SECRETARÍA DE SEGURIDAD PÚBLICA Y TRÁNSITO MUNICIPAL",
  },
  {
    id: 24,
    secretaria_id: 10,
    active: true,
    name: "direccion_de_geografia_y_estadistica",
    display_name: "DIRECCIÓN DE GEOGRAFÍA Y ESTADÍSTICA",
  },
  {
    id: 25,
    secretaria_id: 10,
    active: true,
    name: "direccion_de_planeacion_estrategica",
    display_name: "DIRECCIÓN DE PLANEACIÓN ESTRATÉGICA",
  },
  {
    id: 26,
    secretaria_id: 10,
    active: true,
    name: "direccion_de_seguimiento_y_evaluacion",
    display_name: "DIRECCIÓN DE SEGUIMIENTO Y EVALUACIÓN",
  },
  {
    id: 27,
    secretaria_id: 8,
    active: true,
    name: "direccion_de_participacion_ciudadana",
    display_name: "DIRECCIÓN DE PARTICIPACIÓN CIUDADANA",
  },
  {
    id: 28,
    secretaria_id: 10,
    active: true,
    name: "secretaria_de_planeacion",
    display_name: "SECRETARÍA DE PLANEACIÓN",
  },
  {
    id: 29,
    secretaria_id: 8,
    active: true,
    name: "direccion_para_el_desarrollo_del_bienestar_social",
    display_name: "DIRECCIÓN PARA EL DESARROLLO DEL BIENESTAR SOCIAL",
  },
  {
    id: 30,
    secretaria_id: 7,
    active: true,
    name: "direccion_de_economia_social_y_solidaria",
    display_name: "DIRECCIÓN DE ECONOMÍA SOCIAL Y SOLIDARIA",
  },
  {
    id: 31,
    secretaria_id: 8,
    active: true,
    name: "direccion_de_servicios_educativos",
    display_name: "DIRECCIÓN DE SERVICIOS EDUCATIVOS",
  },
  {
    id: 32,
    secretaria_id: 8,
    active: true,
    name: "secretaria_de_desarrollo_social_y_educacion",
    display_name: "SECRETARÍA DE DESARROLLO SOCIAL Y EDUCACIÓN",
  },
  {
    id: 33,
    secretaria_id: 7,
    active: true,
    name: "buro_de_turismo_municipal",
    display_name: "BURÓ DE TURISMO MUNICIPAL",
  },
  {
    id: 34,
    secretaria_id: 7,
    active: true,
    name: "direccion_de_fomento_economico",
    display_name: "DIRECCIÓN DE FOMENTO ECONÓMICO",
  },
  {
    id: 35,
    secretaria_id: 7,
    active: true,
    name: "secretaria_de_economia",
    display_name: "SECRETARÍA DE ECONOMÍA",
  },
  {
    id: 36,
    secretaria_id: 9,
    active: true,
    name: "direccion_de_costos_y_concursos",
    display_name: "DIRECCIÓN DE COSTOS Y CONCURSOS",
  },
  {
    id: 37,
    secretaria_id: 9,
    active: true,
    name: "direccion_de_infraestructura",
    display_name: "DIRECCIÓN DE INFRAESTRUCTURA",
  },
  {
    id: 38,
    secretaria_id: 9,
    active: true,
    name: "direccion_de_proyectos",
    display_name: "DIRECCIÓN DE PROYECTOS",
  },
  {
    id: 39,
    secretaria_id: 9,
    active: true,
    name: "secretaria_de_obras_publicas_municipal",
    display_name: "SECRETARÍA DE OBRAS PÚBLICAS MUNICIPAL",
  },
  {
    id: 40,
    secretaria_id: 11,
    active: true,
    name: "clinica_de_diagnostico_de_la_mujer_orientes",
    display_name: "CLÍNICA DE DIAGNÓSTICO DE LA MUJER ORIENTE",
  },
  {
    id: 41,
    secretaria_id: 11,
    active: true,
    name: "direccion_de_proteccion_contra_riesgos_sanitarios",
    display_name: "DIRECCIÓN DE PROTECCIÓN CONTRA RIESGOS SANITARIOS",
  },
  {
    id: 42,
    secretaria_id: 11,
    active: true,
    name: "direccion_de_servicios_medicos",
    display_name: "DIRECCIÓN DE SERVICIOS MÉDICOS",
  },
  {
    id: 43,
    secretaria_id: 11,
    active: true,
    name: "direccion_de_verificaciones_y_claussuras",
    display_name: "DIRECCIÓN DE VERIFICACIONES Y CLAUSSURAS",
  },
  {
    id: 44,
    secretaria_id: 11,
    active: true,
    name: "secretaria_de_salud",
    display_name: "SECRETARÍA DE SALUD",
  },
  {
    id: 45,
    secretaria_id: 6,
    active: true,
    name: "direccion_de_adquisiciones",
    display_name: "DIRECCIÓN DE ADQUISICIONES",
  },
  {
    id: 46,
    secretaria_id: 6,
    active: true,
    name: "direccion_de_recursos_humanos",
    display_name: "DIRECCIÓN DE RECURSOS HUMANOS",
  },
  {
    id: 47,
    secretaria_id: 6,
    active: true,
    name: "direccion_de_rec_materiales_serv_grales_y_patrimonio_mpal",
    display_name: "DIRECCIÓN DE REC. MATERIALES, SERV. GRALES Y PATRIMONIO MPAL.",
  },
  {
    id: 48,
    secretaria_id: 6,
    active: true,
    name: "oficialia_mayor",
    display_name: "OFICIALIA MAYOR",
  },
  {
    id: 49,
    secretaria_id: 13,
    active: true,
    name: "direccion_de_alumbrado_publico",
    display_name: "DIRECCIÓN DE ALUMBRADO PÚBLICO",
  },
  {
    id: 50,
    secretaria_id: 13,
    active: true,
    name: "direccion_de_imagen_urbana_y_areas_verdes",
    display_name: "DIRECCIÓN DE IMAGEN URBANA Y ÁREAS VERDES",
  },
  {
    id: 51,
    secretaria_id: 13,
    active: true,
    name: "direccion_de_imagen_urbana",
    display_name: "DIRECCIÓN DE IMAGEN URBANA",
  },
  {
    id: 52,
    secretaria_id: 13,
    active: true,
    name: "direccion_de_limpia_y_aseo_publico",
    display_name: "DIRECCIÓN DE LIMPIA Y ASEO PÚBLICO",
  },
  {
    id: 53,
    secretaria_id: 13,
    active: true,
    name: "direccion_de_mercados_y_panteones",
    display_name: "DIRECCIÓN DE MERCADOS Y PANTEONES",
  },
  {
    id: 54,
    secretaria_id: 9,
    active: true,
    name: "direccion_de_obras_viales",
    display_name: "DIRECCIÓN DE OBRAS VIALES",
  },
  {
    id: 55,
    secretaria_id: 13,
    active: true,
    name: "secretaria_de_servicios_municipales",
    display_name: "SECRETARÍA DE SERVICIOS MUNICIPALES",
  },
  {
    id: 56,
    secretaria_id: 2,
    active: true,
    name: "contraloria_social",
    display_name: "CONTRALORÍA SOCIAL",
  },
  {
    id: 57,
    secretaria_id: 3,
    active: true,
    name: "secretaria_de_medio_ambiente_y_movilidad_urbana",
    display_name: "SECRETARÍA DE MEDIO AMBIENTE Y MOVILIDAD URBANA",
  },
  {
    id: 58,
    secretaria_id: 4,
    active: true,
    name: "instituto_de_la_juventud",
    display_name: "INSTITUTO DE LA JUVENTUD",
  },
  {
    id: 59,
    secretaria_id: 16,
    active: true,
    name: "tesoreria_municipal",
    display_name: "TESORERÍA MUNICIPAL",
  },
  {
    id: 60,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_1er_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (1ER. REGIDORIA)",
  },
  {
    id: 61,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_2do_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (2DO. REGIDORIA)",
  },
  {
    id: 62,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_3er_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (3ER. REGIDORIA)",
  },
  {
    id: 63,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_4to_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (4TO. REGIDORIA)",
  },
  {
    id: 64,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_5to_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (5TO. REGIDORIA)",
  },
  {
    id: 65,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_6to_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (6TO. REGIDORIA)",
  },
  {
    id: 66,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_7mo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (7MO. REGIDORIA)",
  },
  {
    id: 67,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_8vo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (8VO. REGIDORIA)",
  },
  {
    id: 68,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_9no_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (9NO. REGIDORIA)",
  },
  {
    id: 69,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_10mo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (10MO. REGIDORIA)",
  },
  {
    id: 70,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_11vo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (11VO. REGIDORIA)",
  },
  {
    id: 71,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_12vo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (12VO. REGIDORIA)",
  },
  {
    id: 72,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_13vo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (13VO. REGIDORIA)",
  },
  {
    id: 73,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_14vo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (14VO. REGIDORIA)",
  },
  {
    id: 74,
    secretaria_id: 23,
    active: true,
    name: "instituto_tuxtleco_de_arte_y_cultura",
    display_name: "INSTITUTO TUXTLECO DE ARTE Y CULTURA",
  },
  {
    id: 75,
    secretaria_id: 18,
    active: true,
    name: "direccion_de_ordenamiento_territorial",
    display_name: "DIRECCIÓN DE ORDENAMIENTO TERRITORIAL",
  },
  {
    id: 76,
    secretaria_id: 16,
    active: true,
    name: "coordinacion_general_de_politica_fiscal",
    display_name: "COORDINACIÓN GENERAL DE POLITICA FISCAL",
  },
  {
    id: 77,
    secretaria_id: 19,
    active: true,
    name: "secretaria_para_la_igualdad_de_las_mujeres",
    display_name: "SECRETARÍA PARA LA IGUALDAD DE LAS MUJERES",
  },
  {
    id: 78,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores",
    display_name: "COORDINACIÓN DE REGIDORES",
  },
  {
    id: 79,
    secretaria_id: 14,
    active: true,
    name: "defensoria_municipal_de_los_derechos_humanos",
    display_name: "DEFENSORIA MUNICIPAL DE LOS DERECHOS HUMANOS",
  },
  {
    id: 80,
    secretaria_id: 15,
    active: true,
    name: "direccion_de_asuntos_legales",
    display_name: "DIRECCIÓN DE ASUNTOS LEGALES",
  },
  {
    id: 81,
    secretaria_id: 15,
    active: true,
    name: "direccion_de_control_y_seguimiento_normativo",
    display_name: "DIRECCIÓN DE CONTROL Y SEGUIMIENTO NORMATIVO",
  },
  {
    id: 82,
    secretaria_id: 5,
    active: true,
    name: "secretaria_tecnica_del_presidente",
    display_name: "SECRETARÍA TÉCNICA DEL PRESIDENTE",
  },
  {
    id: 83,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_de_comunicacion_social_y_relaciones_publicas",
    display_name: "COORDINACIÓN DE COMUNICACIÓN SOCIAL Y RELACIONES PÚBLICAS",
  },
  {
    id: 84,
    secretaria_id: 5,
    active: true,
    name: "agencia_municipal_las_granjas",
    display_name: "AGENCIA MUNICIPAL LAS GRANJAS",
  },
  {
    id: 85,
    secretaria_id: 5,
    active: true,
    name: "agencia_municipal_teran",
    display_name: "AGENCIA MUNICIPAL TERAN",
  },
  {
    id: 86,
    secretaria_id: 5,
    active: true,
    name: "agencia_municipal_patria_nueva",
    display_name: "AGENCIA MUNICIPAL PATRIA NUEVA",
  },
  {
    id: 87,
    secretaria_id: 16,
    active: true,
    name: "direccion_financiera_y_contable",
    display_name: "DIRECCIÓN FINANCIERA Y CONTABLE",
  },
  {
    id: 88,
    secretaria_id: 16,
    active: true,
    name: "direccion_de_financiamiento_para_el_desarrollo",
    display_name: "DIRECCIÓN DE FINANCIAMIENTO PARA EL DESARROLLO",
  },
  {
    id: 89,
    secretaria_id: 20,
    active: true,
    name: "instituto_del_deporte_tuxtleco",
    display_name: "INSTITUTO DEL DEPORTE TUXTLECO",
  },
  {
    id: 90,
    secretaria_id: 13,
    active: true,
    name: "mercado_22_de_noviembre_patria_nueva",
    display_name: "MERCADO 22 DE NOVIEMBRE (PATRIA NUEVA)",
  },
  {
    id: 91,
    secretaria_id: 13,
    active: true,
    name: "mercado_24_de_junio",
    display_name: "MERCADO 24 DE JUNIO",
  },
  {
    id: 92,
    secretaria_id: 13,
    active: true,
    name: "mercado_5_de_mayo",
    display_name: "MERCADO 5 DE MAYO",
  },
  {
    id: 93,
    secretaria_id: 13,
    active: true,
    name: "mercado_albania_baja",
    display_name: "MERCADO ALBANIA BAJA",
  },
  {
    id: 94,
    secretaria_id: 13,
    active: true,
    name: "mercado_andador_san_roque",
    display_name: "MERCADO ANDADOR SAN ROQUE",
  },
  {
    id: 95,
    secretaria_id: 13,
    active: true,
    name: "mercado_del_norte",
    display_name: "MERCADO DEL NORTE",
  },
  {
    id: 96,
    secretaria_id: 13,
    active: true,
    name: "mercado_juan_sabines",
    display_name: "MERCADO JUAN SABINES",
  },
  {
    id: 97,
    secretaria_id: 13,
    active: true,
    name: "mercado_dr_rafael_pascacio_gamboa",
    display_name: "MERCADO DR. RAFAEL PASCACIO GAMBOA",
  },
  {
    id: 98,
    secretaria_id: 13,
    active: true,
    name: "mercado_san_juan",
    display_name: "MERCADO SAN JUAN",
  },
  {
    id: 99,
    secretaria_id: 13,
    active: true,
    name: "mercado_santa_cruz_teran",
    display_name: "MERCADO SANTA CRUZ (TERÁN)",
  },
  {
    id: 100,
    secretaria_id: 11,
    active: true,
    name: "direccion_de_verificaciones_y_clausuras",
    display_name: "DIRECCIÓN DE VERIFICACIONES Y CLAUSURAS",
  },
  {
    id: 101,
    secretaria_id: 11,
    active: true,
    name: "direccion_de_la_clinica_de_diagnostico_de_la_mujer_oriente",
    display_name: "DIRECCIÓN DE LA CLÍNICA DE DIAGNÓSTICO DE LA MUJER ORIENTE",
  },
  {
    id: 102,
    secretaria_id: 21,
    active: true,
    name: "secretaria_de_proteccion_civil",
    display_name: "SECRETARÍA DE PROTECCIÓN CIVIL",
  },
  {
    id: 103,
    secretaria_id: 8,
    active: true,
    name: "direccion_de_desarrollo_comunitario",
    display_name: "DIRECCIÓN DE DESARROLLO COMUNITARIO",
  },
  {
    id: 104,
    secretaria_id: 5,
    active: true,
    name: "agencia_municipal_copoya",
    display_name: "AGENCIA MUNICIPAL COPOYA",
  },
  {
    id: 105,
    secretaria_id: 5,
    active: true,
    name: "agencia_municipal_emiliano_zapata",
    display_name: "AGENCIA MUNICIPAL EMILIANO ZAPATA",
  },
  {
    id: 106,
    secretaria_id: 5,
    active: true,
    name: "agencia_municipal_cerro_hueco",
    display_name: "AGENCIA MUNICIPAL CERRO HUECO",
  },
  {
    id: 107,
    secretaria_id: 5,
    active: true,
    name: "agencia_municipal_san_jose_teran",
    display_name: "AGENCIA MUNICIPAL SAN JOSÉ TERÁN",
  },
  {
    id: 108,
    secretaria_id: 5,
    active: true,
    name: "agencia_municipal_el_jobo",
    display_name: "AGENCIA MUNICIPAL EL JOBO",
  },
  {
    id: 109,
    secretaria_id: 5,
    active: true,
    name: "agencia_municipal_francisco_i_madero",
    display_name: "AGENCIA MUNICIPAL FRANCISCO I. MADERO",
  },
  {
    id: 110,
    secretaria_id: 5,
    active: true,
    name: "agencia_municipal_plan_de_ayala",
    display_name: "AGENCIA MUNICIPAL PLAN DE AYALA",
  },
  {
    id: 111,
    secretaria_id: 18,
    active: true,
    name: "direccion_de_procedimientos_juridicos",
    display_name: "DIRECCIÓN DE PROCEDIMIENTOS JURÍDICOS",
  },
  {
    id: 112,
    secretaria_id: 3,
    active: true,
    name: "direccion_de_proyectos_ambientales_y_cambios_climaticos",
    display_name: "DIRECCIÓN DE PROYECTOS AMBIENTALES Y CAMBIOS CLIMÁTICOS",
  },
  {
    id: 113,
    secretaria_id: 3,
    active: true,
    name: "direccion_de_movilidad_urbana_y_educacion_ambiental",
    display_name: "DIRECCIÓN DE MOVILIDAD URBANA Y EDUCACIÓN AMBIENTAL",
  },
  {
    id: 114,
    secretaria_id: 19,
    active: true,
    name: "direccion_de_promocion_de_la_igualdad",
    display_name: "DIRECCIÓN DE PROMOCIÓN DE LA IGUALDAD",
  },
  {
    id: 115,
    secretaria_id: 8,
    active: true,
    name: "direccion_de_inclusion_y_cohesion_social",
    display_name: "DIRECCIÓN DE INCLUSIÓN Y COHESIÓN SOCIAL",
  },
  {
    id: 116,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_de_mejora_regulatoria",
    display_name: "COORDINACIÓN DE MEJORA REGULATORIA",
  },
  {
    id: 117,
    secretaria_id: 3,
    active: true,
    name: "direccion_juridica_ambiental",
    display_name: "DIRECCIÓN JURÍDICA AMBIENTAL",
  },
  {
    id: 118,
    secretaria_id: 7,
    active: true,
    name: "direccion_de_fomento_rural",
    display_name: "DIRECCIÓN DE FOMENTO RURAL",
  },
  {
    id: 119,
    secretaria_id: 22,
    active: true,
    name: "centro_de_cumplimiento_de_sanciones_administrativas",
    display_name: "CENTRO DE CUMPLIMIENTO DE SANCIONES ADMINISTRATIVAS",
  },
  {
    id: 120,
    secretaria_id: 12,
    active: true,
    name: "coordinacion_de_la_policia_ciudadana_solidaria",
    display_name: "COORDINACIÓN DE LA POLICÍA CIUDADANA SOLIDARIA",
  },
  {
    id: 121,
    secretaria_id: 15,
    active: true,
    name: "direccion_de_patrimonio_y_obra_publica",
    display_name: "DIRECCIÓN DE PATRIMONIO Y OBRA PÚBLICA",
  },
  {
    id: 122,
    secretaria_id: 15,
    active: true,
    name: "direccion_de_supervision_de_cuenta_publica",
    display_name: "DIRECCIÓN DE SUPERVISIÓN DE CUENTA PÚBLICA",
  },
  {
    id: 123,
    secretaria_id: 15,
    active: true,
    name: "dir_de_admon_de_emergencias_y_capacitacion",
    display_name: "DIR. DE ADMON. DE EMERGENCIAS Y CAPACITACIÓN",
  },
  {
    id: 124,
    secretaria_id: 1,
    active: true,
    name: "direccion_de_procedimientos_de_responsabilidad_administrativa",
    display_name: "DIRECCIÓN DE PROCEDIMIENTOS DE RESPONSABILIDAD ADMINISTRATIVA",
  },
  {
    id: 125,
    secretaria_id: 10,
    active: true,
    name: "direccion_de_inversion_publica_municipal",
    display_name: "DIRECCIÓN DE INVERSIÓN PÚBLICA MUNICIPAL",
  },
  {
    id: 126,
    secretaria_id: 13,
    active: true,
    name: "coordinacion_administrativa",
    display_name: "COORDINACIÓN ADMINISTRATIVA",
  },
  {
    id: 127,
    secretaria_id: 23,
    active: true,
    name: "cronista_municipal",
    display_name: "CRONISTA MUNICIPAL",
  },
  {
    id: 128,
    secretaria_id: 23,
    active: true,
    name: "direccion_de_bibliotecas_y_desarrollo_cultural",
    display_name: "DIRECCIÓN DE BIBLIOTECAS Y DESARROLLO CULTURAL",
  },
  {
    id: 129,
    secretaria_id: 11,
    active: true,
    name: "direccion_de_la_clinica_de_diagnostico_de_la_mujer_poniente",
    display_name: "DIRECCIÓN DE LA CLÍNICA DE DIAGNÓSTICO DE LA MUJER PONIENTE",
  },
  {
    id: 130,
    secretaria_id: 18,
    active: true,
    name: "direccion_de_control_urbano",
    display_name: "DIRECCIÓN DE CONTROL URBANO",
  },
  {
    id: 131,
    secretaria_id: 11,
    active: true,
    name: "dir_de_identificacion_y_reduccion_de_riesgos_inspecciones_y_eve",
    display_name: "DIR. DE IDENTIFICACIÓN Y REDUCCIÓN DE RIESGOS, INSPECCIONES Y EVE",
  },
  {
    id: 132,
    secretaria_id: 18,
    active: true,
    name: "secretaria_de_desarrollo_urbano_municipal",
    display_name: "SECRETARÍA DE DESARROLLO URBANO MUNICIPAL",
  },
  {
    id: 133,
    secretaria_id: 12,
    active: true,
    name: "direccion_de_transito_transporte_y_vialidad",
    display_name: "DIRECCIÓN DE TRÁNSITO, TRANSPORTE Y VIALIDAD",
  },
  {
    id: 134,
    secretaria_id: 18,
    active: true,
    name: "coordinacion_de_controlgestion_y_seguimiento",
    display_name: "COORDINACIÓN DE CONTROL, GESTIÓN Y SEGUIMIENTO",
  },
  {
    id: 135,
    secretaria_id: 13,
    active: true,
    name: "panteon_municipal",
    display_name: "PANTEÓN MUNICIPAL",
  },
  {
    id: 136,
    secretaria_id: 19,
    active: true,
    name: "direccion_de_planeacion_y_gestion_de_proyectos",
    display_name: "DIRECCIÓN DE PLANEACIÓN Y GESTIÓN DE PROYECTOS",
  },
  {
    id: 137,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_general_de_agencias_y_subagencias_municipales",
    display_name: "COORDINACIÓN GENERAL DE AGENCIAS Y SUBAGENCIAS MUNICIPALES",
  },
  {
    id: 138,
    secretaria_id: 13,
    active: true,
    name: "panteon_jardin_san_marcos",
    display_name: "PANTEÓN JARDÍN (SAN MARCOS)",
  },
  {
    id: 139,
    secretaria_id: 6,
    active: true,
    name: "pensionados",
    display_name: "PENSIONADOS",
  },
  {
    id: 140,
    secretaria_id: 17,
    active: true,
    name: "sala_de_regidores",
    display_name: "SALA DE REGIDORES",
  },
];

module.exports = direccion;
