const direccion = [
  {
    id: 1,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_de_asesores",
    display_name: "COORDINACIÓN DE ASESORES",
  },
  {
    id: 2,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_de_relaciones_interinstitucional",
    display_name: "COORDINACIÓN DE RELACIONES INTERINSTITUCIONAL",
  },
  {
    id: 3,
    secretaria_id: 5,
    active: true,
    name: "secretaria_particular_del_despacho_del_presidente",
    display_name: "SECRETARÍA PARTICULAR DEL DESPACHO DEL PRESIDENTE",
  },
  {
    id: 4,
    secretaria_id: 5,
    active: true,
    name: "presidencia_municipal",
    display_name: "PRESIDENCIA MUNICIPAL",
  },
  {
    id: 5,
    secretaria_id: 15,
    active: true,
    name: "sindicatura",
    display_name: "SINDICATURA",
  },
  {
    id: 6,
    secretaria_id: 1,
    active: true,
    name: "direccion_de_auditorias_a_fonds_de_aportaciones_federales_estatales_y_municipales",
    display_name: "DIRECCIÓN DE AUDITORÍAS A FONDS DE APORTACIONES FEDERALES ESTATALES Y MUNICIPALES",
  },
  {
    id: 7,
    secretaria_id: 1,
    active: true,
    name: "direccion_de_auditorias_administrativas_y_financieras",
    display_name: "DIRECCIÓN DE AUDITORÍAS ADMINISTRATIVAS Y FINANCIERAS",
  },
  {
    id: 8,
    secretaria_id: 1,
    active: true,
    name: "direccion_de_verificacion_y_auditoria_a_la_obra_publica",
    display_name: "DIRECCIÓN DE VERIFICACIÓN Y AUDITORÍA A LA OBRA PÚBLICA",
  },
  {
    id: 9,
    secretaria_id: 1,
    active: true,
    name: "direccion_de_investigacion_de_faltas_administrativas_y_evolucion_patrimonial",
    display_name: "DIRECCIÓN DE INVESTIGACIÓN DE FALTAS ADMINISTRATIVAS Y EVOLUCIÓN PATRIMONIAL",
  },
  {
    id: 10,
    secretaria_id: 1,
    active: true,
    name: "contraloria_municipal",
    display_name: "CONTRALORÍA MUNICIPAL",
  },
  {
    id: 11,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_general_de_gabinete_y_atencion_ciudadana",
    display_name: "COORDINACIÓN GENERAL DE GABINETE Y ATENCION CIUDADANA",
  },
  {
    id: 12,
    secretaria_id: 14,
    active: true,
    name: "direccion_de_gobierno",
    display_name: "DIRECCIÓN DE GOBIERNO",
  },
  {
    id: 13,
    secretaria_id: 14,
    active: true,
    name: "direccion_de_tenencia_de_la_tierra",
    display_name: "DIRECCIÓN DE TENENCIA DE LA TIERRA",
  },
  {
    id: 14,
    secretaria_id: 14,
    active: true,
    name: "direccion_del_ayuntamiento",
    display_name: "DIRECCIÓN DEL AYUNTAMIENTO",
  },
  {
    id: 15,
    secretaria_id: 5,
    active: true,
    name: "consejeria_juridica",
    display_name: "CONSEJERÍA JURÍDICA",
  },
  {
    id: 16,
    secretaria_id: 14,
    active: true,
    name: "secretaria_general_del_ayuntamiento",
    display_name: "SECRETARÍA GENERAL DEL AYUNTAMIENTO",
  },
  {
    id: 17,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_general_de_la_unidad_de_transparencia",
    display_name: "COORDINACIÓN GENERAL DE LA UNIDAD DE TRANSPARENCIA",
  },
  {
    id: 18,
    secretaria_id: 5,
    active: true,
    name: "coordinacion_de_tecnologias_de_la_informacion_y_comunicaciones",
    display_name: "COORDINACIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIONES",
  },
  {
    id: 19,
    secretaria_id: 12,
    active: true,
    name: "coordinacion_de_prevencion_del_delito",
    display_name: "COORDINACIÓN DE PREVENCIÓN DEL DELITO",
  },
  {
    id: 20,
    secretaria_id: 12,
    active: true,
    name: "direccion_de_seguridad_publica",
    display_name: "DIRECCIÓN DE SEGURIDAD PÚBLICA",
  },
  {
    id: 21,
    secretaria_id: 12,
    active: true,
    name: "direccion_de_transito",
    display_name: "DIRECCIÓN DE TRÁNSITO",
  },
  {
    id: 22,
    secretaria_id: 12,
    active: true,
    name: "direccion_de_transporte",
    display_name: "DIRECCIÓN DE TRANSPORTE",
  },
  {
    id: 23,
    secretaria_id: 12,
    active: true,
    name: "secretaria_de_seguridad_publica_y_transito_municipal",
    display_name: "SECRETARÍA DE SEGURIDAD PÚBLICA Y TRÁNSITO MUNICIPAL",
  },
  {
    id: 24,
    secretaria_id: 10,
    active: true,
    name: "direccion_de_geografia_y_estadistica",
    display_name: "DIRECCIÓN DE GEOGRAFÍA Y ESTADÍSTICA",
  },
  {
    id: 25,
    secretaria_id: 10,
    active: true,
    name: "direccion_de_planeacion_estrategica",
    display_name: "DIRECCIÓN DE PLANEACIÓN ESTRATÉGICA",
  },
  {
    id: 26,
    secretaria_id: 10,
    active: true,
    name: "direccion_de_seguimiento_y_evaluacion",
    display_name: "DIRECCIÓN DE SEGUIMIENTO Y EVALUACIÓN",
  },
  {
    id: 27,
    secretaria_id: 8,
    active: true,
    name: "direccion_de_participacion_ciudadana",
    display_name: "DIRECCIÓN DE PARTICIPACIÓN CIUDADANA",
  },
  {
    id: 28,
    secretaria_id: 10,
    active: true,
    name: "secretaria_de_planeacion",
    display_name: "SECRETARÍA DE PLANEACIÓN",
  },
  {
    id: 29,
    secretaria_id: 8,
    active: true,
    name: "direccion_para_el_desarrollo_del_bienestar_social",
    display_name: "DIRECCIÓN PARA EL DESARROLLO DEL BIENESTAR SOCIAL",
  },
  {
    id: 30,
    secretaria_id: 7,
    active: true,
    name: "direccion_de_economia_social_y_solidaria",
    display_name: "DIRECCIÓN DE ECONOMÍA SOCIAL Y SOLIDARIA",
  },
  {
    id: 31,
    secretaria_id: 8,
    active: true,
    name: "direccion_de_servicios_educativos",
    display_name: "DIRECCIÓN DE SERVICIOS EDUCATIVOS",
  },
  {
    id: 32,
    secretaria_id: 8,
    active: true,
    name: "secretaria_de_desarrollo_social_y_educacion",
    display_name: "SECRETARÍA DE DESARROLLO SOCIAL Y EDUCACIÓN",
  },
  {
    id: 33,
    secretaria_id: 7,
    active: true,
    name: "buro_de_turismo_municipal",
    display_name: "BURÓ DE TURISMO MUNICIPAL",
  },
  {
    id: 34,
    secretaria_id: 7,
    active: true,
    name: "direccion_de_fomento_economico",
    display_name: "DIRECCIÓN DE FOMENTO ECONÓMICO",
  },
  {
    id: 35,
    secretaria_id: 7,
    active: true,
    name: "secretaria_de_economia",
    display_name: "SECRETARÍA DE ECONOMÍA",
  },
  {
    id: 36,
    secretaria_id: 9,
    active: true,
    name: "direccion_de_costos_y_concursos",
    display_name: "DIRECCIÓN DE COSTOS Y CONCURSOS",
  },
  {
    id: 37,
    secretaria_id: 9,
    active: true,
    name: "direccion_de_infraestructura",
    display_name: "DIRECCIÓN DE INFRAESTRUCTURA",
  },
  {
    id: 38,
    secretaria_id: 9,
    active: true,
    name: "direccion_de_proyectos",
    display_name: "DIRECCIÓN DE PROYECTOS",
  },
  {
    id: 39,
    secretaria_id: 9,
    active: true,
    name: "secretaria_de_obras_publicas",
    display_name: "SECRETARÍA DE OBRAS PÚBLICAS",
  },
  {
    id: 40,
    secretaria_id: 11,
    active: true,
    name: "clinica_de_diagnostico_de_la_mujer_orientes",
    display_name: "CLÍNICA DE DIAGNÓSTICO DE LA MUJER ORIENTES",
  },
  {
    id: 41,
    secretaria_id: 11,
    active: true,
    name: "direccion_de_proteccion_contra_riesgos_sanitarios",
    display_name: "DIRECCIÓN DE PROTECCIÓN CONTRA RIESGOS SANITARIOS",
  },
  {
    id: 42,
    secretaria_id: 11,
    active: true,
    name: "direccion_de_servicios_medicos",
    display_name: "DIRECCIÓN DE SERVICIOS MÉDICOS",
  },
  {
    id: 43,
    secretaria_id: 11,
    active: true,
    name: "direccion_de_verificaciones_y_claussuras",
    display_name: "DIRECCIÓN DE VERIFICACIONES Y CLAUSSURAS",
  },
  {
    id: 44,
    secretaria_id: 11,
    active: true,
    name: "secretaria_de_salud",
    display_name: "SECRETARÍA DE SALUD",
  },
  {
    id: 45,
    secretaria_id: 6,
    active: true,
    name: "direccion_de_adquisiciones",
    display_name: "DIRECCIÓN DE ADQUISICIONES",
  },
  {
    id: 46,
    secretaria_id: 6,
    active: true,
    name: "direccion_de_recursos_humanos",
    display_name: "DIRECCIÓN DE RECURSOS HUMANOS",
  },
  {
    id: 47,
    secretaria_id: 6,
    active: true,
    name: "direccion_de_recursos_materiales,_servicios_generales_y_patrimonio_municipal",
    display_name: "DIRECCIÓN DE RECURSOS MATERIALES, SERVICIOS GENERALES Y PATRIMONIO MUNICIPAL",
  },
  {
    id: 48,
    secretaria_id: 6,
    active: true,
    name: "oficialia_mayor",
    display_name: "OFICIALIA MAYOR",
  },
  {
    id: 49,
    secretaria_id: 13,
    active: true,
    name: "direccion_de_alumbrado_publico",
    display_name: "DIRECCIÓN DE ALUMBRADO PÚBLICO",
  },
  {
    id: 50,
    secretaria_id: 13,
    active: true,
    name: "direccion_de_imagen_urbana_y_areas_verdes",
    display_name: "DIRECCIÓN DE IMAGEN URBANA Y ÁREAS VERDES",
  },
  {
    id: 51,
    secretaria_id: 13,
    active: true,
    name: "direccion_de_imagen_urbana",
    display_name: "DIRECCIÓN DE IMAGEN URBANA",
  },
  {
    id: 52,
    secretaria_id: 13,
    active: true,
    name: "direccion_de_limpia_y_aseo_publico",
    display_name: "DIRECCIÓN DE LIMPIA Y ASEO PÚBLICO",
  },
  {
    id: 53,
    secretaria_id: 13,
    active: true,
    name: "direccion_de_mercados_y_panteones",
    display_name: "DIRECCIÓN DE MERCADOS Y PANTEONES",
  },
  {
    id: 54,
    secretaria_id: 9,
    active: true,
    name: "direccion_de_obras_viales",
    display_name: "DIRECCIÓN DE OBRAS VIALES",
  },
  {
    id: 55,
    secretaria_id: 13,
    active: true,
    name: "secretaria_de_servicios_municipales",
    display_name: "SECRETARÍA DE SERVICIOS MUNICIPALES",
  },
  {
    id: 56,
    secretaria_id: 2,
    active: true,
    name: "contraloria_social",
    display_name: "CONTRALORÍA SOCIAL",
  },
  {
    id: 57,
    secretaria_id: 3,
    active: true,
    name: "secretaria_de_medio_ambiente_y_movilidad_urbana",
    display_name: "SECRETARÍA DE MEDIO AMBIENTE Y MOVILIDAD URBANA",
  },
  {
    id: 58,
    secretaria_id: 4,
    active: true,
    name: "instituto_de_la_juventud",
    display_name: "INSTITUTO DE LA JUVENTUD",
  },
  {
    id: 59,
    secretaria_id: 16,
    active: true,
    name: "tesoreria_municipal",
    display_name: "TESORERÍA MUNICIPAL",
  },
  {
    id: 60,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_1er_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (1ER. REGIDORIA)",
  },
  {
    id: 61,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_2do_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (2DO. REGIDORIA)",
  },
  {
    id: 62,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_3er_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (3ER. REGIDORIA)",
  },
  {
    id: 63,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_4to_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (4TO. REGIDORIA)",
  },
  {
    id: 64,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_5to_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (5TO. REGIDORIA)",
  },
  {
    id: 65,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_6to_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (6TO. REGIDORIA)",
  },
  {
    id: 66,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_7mo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (7MO. REGIDORIA)",
  },
  {
    id: 67,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_8vo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (8VO. REGIDORIA)",
  },
  {
    id: 68,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_9no_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (9NO. REGIDORIA)",
  },
  {
    id: 69,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_10mo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (10MO. REGIDORIA)",
  },
  {
    id: 70,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_11vo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (11VO. REGIDORIA)",
  },
  {
    id: 71,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_12vo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (12VO. REGIDORIA)",
  },
  {
    id: 72,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_13vo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (13VO. REGIDORIA)",
  },
  {
    id: 73,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores_14vo_regidoria",
    display_name: "COORDINACIÓN DE REGIDORES (14VO. REGIDORIA)",
  },
  {
    id: 74,
    secretaria_id: 8,
    active: true,
    name: "instituto_tuxtleco_de_arte_y_cultura",
    display_name: "INSTITUTO TUXTLECO DE ARTE Y CULTURA",
  },
  {
    id: 75,
    secretaria_id: 18,
    active: true,
    name: "direccion_de_ordenamiento_territorial",
    display_name: "DIRECCION DE ORDENAMIENTO TERRITORIAL",
  },
  {
    id: 76,
    secretaria_id: 16,
    active: true,
    name: "coordinacion_general_de_politica_fiscal",
    display_name: "COORDINACION GENERAL DE POLITICA FISCAL",
  },
  {
    id: 77,
    secretaria_id: 19,
    active: true,
    name: "secretaria_para_la_igualdad_de_las_mujeres",
    display_name: "SECRETARIA PARA LA IGUALDAD DE LAS MUJERES",
  },
  {
    id: 78,
    secretaria_id: 17,
    active: true,
    name: "coordinacion_de_regidores",
    display_name: "COORDINACIÓN DE REGIDORES",
  },
  {
    id: 79,
    secretaria_id: 14,
    active: true,
    name: "defensoria_municipal_de_los_derechos_humanos",
    display_name: "DEFENSORIA MUNICIPAL DE LOS DERECHOS HUMANOS",
  },
  {
    id: 80,
    secretaria_id: 15,
    active: true,
    name: "direccion_de_asuntos_legales",
    display_name: "DIRECCION DE ASUNTOS LEGALES",
  },
  {
    id: 81,
    secretaria_id: 15,
    active: true,
    name: "direccion_de_control_y_seguimiento_normativo",
    display_name: "DIRECCION DE CONTROL Y SEGUIMIENTO NORMATIVO",
  },
];

module.exports = direccion;
