const incidentStatus = [
  {
    id: 1,
    name: "creada",
    display_name: "CREADA",
    btn_display_name: "Creada",
    btn_icon: "clock",
    btn_color: "warning",
    type: 1,
    active: true,
    permission_name: "",
  },
  {
    id: 2,
    name: "validada",
    display_name: "VALIDADA",
    btn_display_name: "Validada",
    btn_icon: "check",
    btn_color: "primary",
    type: 1,
    active: true,
    permission_name: "can_validate",
  },
  {
    id: 3,
    name: "aprobada",
    display_name: "APROBADA",
    btn_display_name: "Aprobada",
    btn_icon: "check",
    btn_color: "success",
    type: 1,
    active: true,
    permission_name: "can_approve",
  },
  {
    id: 4,
    name: "rechazada",
    display_name: "RECHAZADA",
    btn_display_name: "Rechazada",
    btn_icon: "x",
    btn_color: "error",
    type: 1,
    active: true,
    permission_name: "can_reject",
  },
  {
    id: 5,
    name: "eliminada",
    display_name: "ELIMINADA",
    btn_display_name: "Eliminada",
    btn_icon: "trash",
    btn_color: "warning",
    type: 1,
    active: true,
    permission_name: "can_delete",
  },
  {
    id: 6,
    name: "cancelada",
    display_name: "CANCELADA",
    btn_display_name: "Cancelada",
    btn_icon: "x",
    btn_color: "error",
    type: 1,
    active: true,
    permission_name: "can_cancel",
  },
];

module.exports = incidentStatus;
