const incidentStatus = [
  {
    id: 1,
    name: "creada",
    display_name: "CREADA",
    btn_display_name: "Creada",
    btn_icon: "clock",
    btn_color: "warning",
    type: 1,
    active: true,
  },
  {
    id: 2,
    name: "aprobada",
    display_name: "APROBADA",
    btn_display_name: "Aprobada",
    btn_icon: "check",
    btn_color: "success",
    type: 1,
    active: true,
  },
  {
    id: 3,
    name: "rechazada",
    display_name: "RECHAZADA",
    btn_display_name: "Rechazada",
    btn_icon: "x",
    btn_color: "error",
    type: 1,
    active: true,
  },
  {
    id: 4,
    name: "eliminada",
    display_name: "ELIMINADA",
    btn_display_name: "Eliminada",
    btn_icon: "trash",
    btn_color: "warning",
    type: 1,
    active: true,
  },
  {
    id: 5,
    name: "cancelada",
    display_name: "CANCELADA",
    btn_display_name: "Cancelada",
    btn_icon: "x",
    btn_color: "error",
    type: 1,
    active: true,
  },
];

module.exports = incidentStatus;
