const baseSindicalizadoRules = [
  {
    incident_id: 10,
    employee_type_id: 1,
    days: 10,
    start_date: 1,
    end_date: 6,
    min_years: 1,
    max_years: 5,
    active: true,
  },
  {
    incident_id: 10,
    employee_type_id: 1,
    days: 10,
    start_date: 7,
    end_date: 12,
    min_years: 1,
    max_years: 5,
    active: true,
  },
  {
    incident_id: 10,
    employee_type_id: 1,
    days: 13,
    start_date: 1,
    end_date: 6,
    min_years: 6,
    active: true,
  },
  {
    incident_id: 10,
    employee_type_id: 1,
    days: 13,
    start_date: 7,
    end_date: 12,
    min_years: 6,
    active: true,
  },
];

const baseNoSindicalizadoRules = [
  {
    incident_id: 10,
    employee_type_id: 2,
    days: 10,
    start_date: 1,
    end_date: 6,
    min_years: 1,
    max_years: 5,
    active: true,
  },
  {
    incident_id: 10,
    employee_type_id: 2,
    days: 10,
    start_date: 7,
    end_date: 12,
    min_years: 1,
    max_years: 5,
    active: true,
  },
  {
    incident_id: 10,
    employee_type_id: 2,
    days: 13,
    start_date: 1,
    end_date: 6,
    min_years: 6,
    active: true,
  },
  {
    incident_id: 10,
    employee_type_id: 2,
    days: 13,
    start_date: 7,
    end_date: 12,
    min_years: 6,
    active: true,
  },
];

const confianzaRules = [
  {
    incident_id: 10,
    employee_type_id: 3,
    days: 10,
    start_date: 1,
    end_date: 6,
    min_years: 1,
    max_years: 5,
    active: true,
  },
  {
    incident_id: 10,
    employee_type_id: 3,
    days: 10,
    start_date: 7,
    end_date: 12,
    min_years: 1,
    max_years: 5,
    active: true,
  },
  {
    incident_id: 10,
    employee_type_id: 3,
    days: 13,
    start_date: 1,
    end_date: 6,
    min_years: 6,
    active: true,
  },
  {
    incident_id: 10,
    employee_type_id: 3,
    days: 13,
    start_date: 7,
    end_date: 12,
    min_years: 6,
    active: true,
  },
];

const contratoLaudoRules = [
  {
    incident_id: 10,
    employee_type_id: 5,
    days: 13,
    start_date: 1,
    end_date: 6,
    min_years: 6,
    active: true,
  },
  {
    incident_id: 10,
    employee_type_id: 5,
    days: 13,
    start_date: 7,
    end_date: 12,
    min_years: 6,
    active: true,
  },
];

module.exports = [...baseSindicalizadoRules, ...baseNoSindicalizadoRules, ...confianzaRules, ...contratoLaudoRules];
