const incident = [
  {
    id: 1,
    name: "incapacidad",
    display_name: "INCAPACIDADES",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: false,
    bgColorOnCalendar: "secondary.main",
  },
  {
    id: 2,
    name: "justificacion_entrada",
    display_name: "JUSTIFICACION DE ENTRADA",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: true,
    bgColorOnCalendar: "warning.main",
  },
  {
    id: 3,
    name: "justificacion_salida",
    display_name: "JUSTIFICACION DE SALIDA",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: true,
    bgColorOnCalendar: "warning.main",
  },
  {
    id: 4,
    name: "justificacion_entrada_salida",
    display_name: "JUSTIFICACION DE ENTRADA Y SALIDA",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: true,
    bgColorOnCalendar: "warning.main",
  },
  {
    id: 5,
    name: "lactancia",
    display_name: "LACTANCIA",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: false,
    bgColorOnCalendar: "warning.main",
  },
  {
    id: 6,
    name: "paternidad",
    display_name: "PATERNIDAD",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: false,
    bgColorOnCalendar: "warning.main",
  },
  {
    id: 7,
    name: "permiso_especial",
    display_name: "PERMISO ESPECIAL",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: false,
    bgColorOnCalendar: "warning.main",
  },
  {
    id: 8,
    name: "permiso_economico",
    display_name: "PERMISOS ECONOMICOS",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: false,
    bgColorOnCalendar: "warning.main",
  },
  {
    id: 9,
    name: "permiso_sin_goce",
    display_name: "PERMISOS SIN GOCE",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: false,
    bgColorOnCalendar: "warning.main",
  },
  {
    id: 10,
    name: "vacaciones",
    display_name: "VACACIONES",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: false,
    bgColorOnCalendar: "warning.main",
  },
  {
    id: 11,
    name: "comision",
    display_name: "COMISION",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: false,
    bgColorOnCalendar: "warning.main",
  },
  {
    id: 12,
    name: "retardo",
    display_name: "RETARDO",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: true,
    bgColorOnCalendar: "warning.main",
  },
  {
    id: 13,
    name: "falta",
    display_name: "FALTA",
    type: 1,
    active: true,
    display_calendar_dates: true,
    display_time_on_calendar: false,
    bgColorOnCalendar: "error.attendance",
  },
];
module.exports = incident;
