const locations = [
  { id: 1, name: "agencia_cerro_hueco", display_name: "AGENCIA CERRO HUECO" },
  { id: 2, name: "agencia_copoya", display_name: "AGENCIA COPOYA" },
  { id: 3, name: "agencia_el_jobo", display_name: "AGENCIA EL JOBO" },
  { id: 4, name: "agencia_emiliano_zapata", display_name: "AGENCIA EMILIANO ZAPATA" },
  { id: 5, name: "agencia_francisco_i_madero", display_name: "AGENCIA FRANCISCO I MADERO" },
  { id: 6, name: "agencia_las_granjas", display_name: "AGENCIA LAS GRANJAS" },
  { id: 7, name: "agencia_patria_nueva", display_name: "AGENCIA PATRIA NUEVA" },
  { id: 8, name: "agencia_plan_de_ayala", display_name: "AGENCIA PLAN DE AYALA" },
  { id: 9, name: "agencia_real_del_bosque", display_name: "AGENCIA REAL DEL BOSQUE" },
  { id: 10, name: "agencia_san_jose_teran", display_name: "AGENCIA SAN JOSE TERAN" },
  { id: 11, name: "agencia_teran", display_name: "AGENCIA TERAN" },
  { id: 12, name: "avenida_central_entre_1a_y_2a_oriente", display_name: "AVENIDA CENTRAL ENTRE 1A Y 2A ORIENTE" },
  {
    id: 13,
    name: "avenida_central_entre_1a_y_2a_oriente_fiscales",
    display_name: "AVENIDA CENTRAL ENTRE 1A Y 2A ORIENTE FISCALES",
  },
  { id: 14, name: "base_teran", display_name: "BASE TERAN" },
  { id: 15, name: "biblioteca_24_de_junio", display_name: "BIBLIOTECA 24 DE JUNIO" },
  { id: 16, name: "biblioteca_albania_alta", display_name: "BIBLIOTECA ALBANIA ALTA" },
  { id: 17, name: "biblioteca_calz_h_ilustres", display_name: "BIBLIOTECA CALZ. H. ILUSTRES" },
  { id: 18, name: "biblioteca_cerro_hueco", display_name: "BIBLIOTECA CERRO HUECO" },
  { id: 19, name: "biblioteca_copoya", display_name: "BIBLIOTECA COPOYA" },
  { id: 20, name: "biblioteca_el_jobo", display_name: "BIBLIOTECA EL JOBO" },
  { id: 21, name: "biblioteca_emiliano_zapata", display_name: "BIBLIOTECA EMILIANO ZAPATA" },
  { id: 22, name: "biblioteca_las_granjas", display_name: "BIBLIOTECA LAS GRANJAS" },
  { id: 23, name: "biblioteca_nino_de_atocha", display_name: "BIBLIOTECA NIÑO DE ATOCHA" },
  { id: 24, name: "biblioteca_patria_nueva", display_name: "BIBLIOTECA PATRIA NUEVA" },
  { id: 25, name: "biblioteca_ruben_lopez_carcamo", display_name: "BIBLIOTECA RUBEN LOPEZ CARCAMO" },
  { id: 26, name: "biblioteca_san_jose_teran", display_name: "BIBLIOTECA SAN JOSE TERAN" },
  { id: 27, name: "biblioteca_san_roque", display_name: "BIBLIOTECA SAN ROQUE" },
  { id: 28, name: "biblioteca_teran", display_name: "BIBLIOTECA TERAN" },
  { id: 29, name: "calzada_hombres_ilustres", display_name: "CALZADA HOMBRES ILUSTRES" },
  { id: 30, name: "casa_cultural_teran", display_name: "CASA CULTURAL TERAN" },
  { id: 31, name: "cana_hueca_cavip", display_name: "CAÑA HUECA CAVIP" },
  { id: 32, name: "clinica_de_la_mujer_ote", display_name: "CLINICA DE LA MUJER OTE" },
  { id: 33, name: "clinica_de_la_mujer_pte", display_name: "CLINICA DE LA MUJER PTE" },
  { id: 34, name: "colonia_moctezuma", display_name: "COLONIA MOCTEZUMA" },
  { id: 35, name: "convivencia_infantil_agencia", display_name: "CONVIVENCIA INFANTIL AGENCIA" },
  {
    id: 36,
    name: "convivencia_infantil_estacionamiento_y_banos",
    display_name: "CONVIVENCIA INFANTIL ESTACIONAMIENTO Y BAÑOS",
  },
  { id: 37, name: "convivencia_infantil_juventud", display_name: "CONVIVENCIA INFANTIL JUVENTUD" },
  { id: 38, name: "convivencia_infantil_prevencion", display_name: "CONVIVENCIA INFANTIL PREVENCION" },
  { id: 39, name: "convivencia_infantil_sedesol", display_name: "CONVIVENCIA INFANTIL SEDESOL" },
  {
    id: 40,
    name: "convivencia_infantil_sedesol_cedeco_24_de_junio",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO 24 DE JUNIO",
  },
  {
    id: 41,
    name: "convivencia_infantil_sedesol_cedeco_albergue_dor",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO ALBERGUE DOR",
  },
  {
    id: 42,
    name: "convivencia_infantil_sedesol_cedeco_cai_cruz_con",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO CAI CRUZ CON",
  },
  {
    id: 43,
    name: "convivencia_infantil_sedesol_cedeco_cai_insurgen",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO CAI INSURGEN",
  },
  {
    id: 44,
    name: "convivencia_infantil_sedesol_cedeco_casa_del_abu",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO CASA DEL ABU",
  },
  {
    id: 45,
    name: "convivencia_infantil_sedesol_cedeco_casa_taller",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO CASA TALLER",
  },
  {
    id: 46,
    name: "convivencia_infantil_sedesol_cedeco_cemtri",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO CEMTRI",
  },
  {
    id: 47,
    name: "convivencia_infantil_sedesol_cedeco_copoya",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO COPOYA",
  },
  {
    id: 48,
    name: "convivencia_infantil_sedesol_cedeco_km4",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO KM4",
  },
  {
    id: 49,
    name: "convivencia_infantil_sedesol_cedeco_la_democrati",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO LA DEMOCRATI",
  },
  {
    id: 50,
    name: "convivencia_infantil_sedesol_cedeco_la_mision",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO LA MISION",
  },
  {
    id: 51,
    name: "convivencia_infantil_sedesol_cedeco_las_granjas",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO LAS GRANJAS",
  },
  {
    id: 52,
    name: "convivencia_infantil_sedesol_cedeco_los_pajaros",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO LOS PAJAROS",
  },
  {
    id: 53,
    name: "convivencia_infantil_sedesol_cedeco_patria_nueva",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO PATRIA NUEVA",
  },
  {
    id: 54,
    name: "convivencia_infantil_sedesol_cedeco_plan_de_ayal",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO PLAN DE AYAL",
  },
  {
    id: 55,
    name: "convivencia_infantil_sedesol_cedeco_teran",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO TERAN",
  },
  {
    id: 56,
    name: "convivencia_infantil_sedesol_cedeco_unetoc_centr",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CEDECO UNETOC CENTR",
  },
  {
    id: 57,
    name: "convivencia_infantil_sedesol_ciudadano_solidario",
    display_name: "CONVIVENCIA INFANTIL SEDESOL - CIUDADANO SOLIDARIO",
  },
  { id: 58, name: "daec_lib_norte", display_name: "DAEC LIB. NORTE" },
  { id: 59, name: "daec_potrero_mirador", display_name: "DAEC POTRERO MIRADOR" },
  { id: 60, name: "dirrie", display_name: "DIRRIE" },
  { id: 61, name: "dirrie_potrero_mirador", display_name: "DIRRIE POTRERO MIRADOR" },
  { id: 62, name: "edif_desarrollo_urb", display_name: "EDIF. DESARROLLO URB" },
  { id: 63, name: "edificio_de_la_sspytm", display_name: "EDIFICIO DE LA SSPYTM" },
  { id: 64, name: "edificio_valanci", display_name: "EDIFICIO VALANCI" },
  { id: 65, name: "edificio_valanci_dirrie", display_name: "EDIFICIO VALANCI DIRRIE" },
  { id: 66, name: "el_rastro", display_name: "EL RASTRO" },
  { id: 67, name: "el_rastro_direccion", display_name: "EL RASTRO  DIRECCION" },
  { id: 68, name: "el_rastro_alcantarillado", display_name: "EL RASTRO ALCANTARILLADO" },
  { id: 69, name: "el_rastro_cuadrilla", display_name: "EL RASTRO CUADRILLA" },
  { id: 70, name: "el_rastro_maquinaria", display_name: "EL RASTRO MAQUINARIA" },
  { id: 71, name: "el_rastro_pavimento", display_name: "EL RASTRO PAVIMENTO" },
  { id: 72, name: "itac", display_name: "ITAC" },
  { id: 73, name: "las_aguilas", display_name: "LAS AGUILAS" },
  { id: 74, name: "limpia_anexo", display_name: "LIMPIA ANEXO" },
  { id: 75, name: "mercado_05_de_mayo", display_name: "MERCADO 05 DE MAYO" },
  { id: 76, name: "mercado_20_de_noviembre", display_name: "MERCADO 20 DE NOVIEMBRE" },
  { id: 77, name: "mercado_22_de_nov_pat_nueva", display_name: "MERCADO 22 DE NOV. (PAT. NUEVA)" },
  { id: 78, name: "mercado_24_de_junio", display_name: "MERCADO 24 DE JUNIO" },
  { id: 79, name: "mercado_albania_baja", display_name: "MERCADO ALBANIA BAJA" },
  { id: 80, name: "mercado_andador_san_roque", display_name: "MERCADO ANDADOR SAN ROQUE" },
  { id: 81, name: "mercado_del_norte", display_name: "MERCADO DEL NORTE" },
  { id: 82, name: "mercado_dr_rafael_pascacio_g", display_name: "MERCADO DR RAFAEL PASCACIO G." },
  { id: 83, name: "mercado_juan_sabines", display_name: "MERCADO JUAN SABINES" },
  { id: 84, name: "mercado_san_juan", display_name: "MERCADO SAN JUAN" },
  { id: 85, name: "mercado_santa_cruz_teran", display_name: "MERCADO SANTA CRUZ TERAN" },
  { id: 86, name: "museo_de_la_marimba", display_name: "MUSEO DE LA MARIMBA" },
  { id: 87, name: "museo_zoque_copoya", display_name: "MUSEO ZOQUE COPOYA" },
  { id: 88, name: "octava_norte", display_name: "OCTAVA NORTE" },
  { id: 89, name: "palacio_municipal", display_name: "PALACIO MUNICIPAL" },
  { id: 90, name: "palacio_municipal_1_regidor", display_name: "PALACIO MUNICIPAL 1 REGIDOR" },
  { id: 91, name: "palacio_municipal_2_regidor", display_name: "PALACIO MUNICIPAL 2 REGIDOR" },
  { id: 92, name: "palacio_municipal_3_regidor", display_name: "PALACIO MUNICIPAL 3 REGIDOR" },
  { id: 93, name: "palacio_municipal_4_regidor", display_name: "PALACIO MUNICIPAL 4 REGIDOR" },
  { id: 94, name: "palacio_municipal_5_regidor", display_name: "PALACIO MUNICIPAL 5 REGIDOR" },
  { id: 95, name: "palacio_municipal_6_regidor", display_name: "PALACIO MUNICIPAL 6 REGIDOR" },
  { id: 96, name: "palacio_municipal_7_regidor", display_name: "PALACIO MUNICIPAL 7 REGIDOR" },
  { id: 97, name: "palacio_municipal_8_regidor", display_name: "PALACIO MUNICIPAL 8 REGIDOR" },
  { id: 98, name: "palacio_municipal_cavip", display_name: "PALACIO MUNICIPAL CAVIP" },
  { id: 99, name: "panteon_jardin_san_marcos", display_name: "PANTEON JARDIN SAN MARCOS" },
  { id: 100, name: "panteon_viejo", display_name: "PANTEON VIEJO" },
  { id: 101, name: "parque_bicentenario", display_name: "PARQUE BICENTENARIO" },
  { id: 102, name: "parque_cana_hueca", display_name: "PARQUE CAÑA HUECA" },
  { id: 103, name: "parque_de_la_marimba", display_name: "PARQUE DE LA MARIMBA" },
  { id: 104, name: "parque_del_oriente", display_name: "PARQUE DEL ORIENTE" },
  { id: 105, name: "parque_del_ote", display_name: "PARQUE DEL OTE" },
  { id: 106, name: "parque_fundamat", display_name: "PARQUE FUNDAMAT" },
  { id: 107, name: "parque_joyyo_mayu", display_name: "PARQUE JOYYO MAYU" },
  { id: 108, name: "parque_los_laureles", display_name: "PARQUE LOS LAURELES" },
  { id: 109, name: "popular", display_name: "POPULAR" },
  { id: 110, name: "rincon_del_arte", display_name: "RINCON DEL ARTE" },
  { id: 111, name: "semaforizacion_col_caminera", display_name: "SEMAFORIZACION COL CAMINERA" },
  { id: 112, name: "sindicato", display_name: "SINDICATO" },
  { id: 113, name: "sitrachisa", display_name: "SITRACHISA" },
  { id: 114, name: "stamt", display_name: "STAMT" },
  { id: 115, name: "stusat", display_name: "STUSAT" },
  { id: 116, name: "sutesa", display_name: "SUTESA" },
  { id: 117, name: "sutsm", display_name: "SUTSM" },
  { id: 118, name: "taller_vehicular_col_santa_ana", display_name: "TALLER VEHICULAR COL SANTA ANA" },
  { id: 119, name: "vivero_municipal", display_name: "VIVERO MUNICIPAL" },
  { id: 120, name: "vivero_municipal_cana_hueca", display_name: "VIVERO MUNICIPAL CAÑA HUECA" },
  { id: 121, name: "vp_hospital_torre_medica", display_name: "VP HOSPITAL - TORRE MEDICA" },
  { id: 122, name: "zona_de_tolerancia", display_name: "ZONA DE TOLERANCIA" },
  { id: 123, name: "parque_tuchtlan", display_name: "PARQUE TUCHTLAN" },
];

module.exports = locations;
