const modules = [
  {
    id: 1,
    name: "inicio",
    display_name: "Inicio",
    route: "/",
    icon: "IconHome2",
    parent_id: null,
  },
  {
    id: 2,
    name: "incidencias",
    display_name: "Incidencias",
    route: "/employees-incidents/",
    icon: "IconAlertCircle",
    parent_id: null,
  },
  {
    id: 3,
    name: "ver_incidencias",
    display_name: "Ver incidencias",
    route: "/admin/employees-incidents",
    icon: "IconPoint",
    parent_id: 2,
  },
  {
    id: 4,
    name: "crear_incidencia",
    display_name: "Crear incidencia",
    route: "/admin/employees-incidents/create",
    icon: "IconPoint",
    parent_id: 2,
  },
  {
    id: 5,
    name: "solicitudes",
    display_name: "Solicitudes",
    route: "/employees-requests/",
    icon: "IconFileInvoice",
    parent_id: null,
  },
  {
    id: 6,
    name: "ver_solicitudes",
    display_name: "Ver solicitudes",
    route: "/admin/employees-requests",
    icon: "IconPoint",
    parent_id: 5,
  },
  {
    id: 7,
    name: "crear_solicitud",
    display_name: "Crear solicitud",
    route: "/admin/employees-requests/create",
    icon: "IconPoint",
    parent_id: 5,
  },
  {
    id: 8,
    name: "empleados",
    display_name: "Empleados",
    route: "/employees/",
    icon: "IconUsers",
    parent_id: null,
  },
  {
    id: 9,
    name: "ver_empleados",
    display_name: "Ver empleados",
    route: "/admin/employees",
    icon: "IconPoint",
    parent_id: 8,
  },
];

module.exports = modules;
