const modules = [
  {
    id: 1,
    name: "inicio",
    display_name: "Inicio",
    route: "/",
    icon: "IconHome2",
    parent_id: null,
  },
  {
    id: 2,
    name: "incidencias",
    display_name: "Incidencias",
    route: "/employees-incidents/",
    icon: "IconAlertCircle",
    parent_id: null,
  },
  {
    id: 3,
    name: "ver_incidencias",
    display_name: "Ver incidencias",
    route: "/admin/employees-incidents",
    icon: "IconPoint",
    parent_id: 2,
  },
  {
    id: 4,
    name: "crear_incidencia",
    display_name: "Crear incidencia",
    route: "/admin/employees-incidents/create",
    icon: "IconPoint",
    parent_id: 2,
  },
  {
    id: 5,
    name: "solicitudes",
    display_name: "Solicitudes",
    route: "/employees-requests/",
    icon: "IconFileInvoice",
    parent_id: null,
  },
  {
    id: 6,
    name: "ver_solicitudes",
    display_name: "Ver solicitudes",
    route: "/admin/employees-requests",
    icon: "IconPoint",
    parent_id: 5,
  },
  {
    id: 7,
    name: "crear_solicitud",
    display_name: "Crear solicitud",
    route: "/admin/employees-requests/create",
    icon: "IconPoint",
    parent_id: 5,
  },
  {
    id: 8,
    name: "empleados",
    display_name: "Empleados",
    route: "/employees/",
    icon: "IconUsers",
    parent_id: null,
  },
  {
    id: 9,
    name: "ver_empleados",
    display_name: "Ver empleados",
    route: "/admin/employees",
    icon: "IconPoint",
    parent_id: 8,
  },
  {
    id: 10,
    name: "crear_empleado",
    display_name: "Crear empleado",
    route: "/admin/employees/create",
    icon: "IconPoint",
    parent_id: 8,
  },
  {
    id: 11,
    name: "usuarios",
    display_name: "Usuarios",
    route: "/admin/users",
    icon: "IconPoint",
    parent_id: null,
  },
  {
    id: 12,
    name: "asistencia",
    display_name: "Asistencia",
    route: "/attendance/",
    icon: "IconPoint",
    parent_id: null,
  },
  {
    id: 13,
    name: "ver_asistencia",
    display_name: "Ver asistencia",
    route: "/admin/employees-attendances",
    icon: "IconPoint",
    parent_id: 12,
  },
  {
    id: 14,
    name: "crear_asistencia",
    display_name: "Crear asistencia",
    route: "/admin/employees-attendances/create",
    icon: "IconPoint",
    parent_id: 12,
  },
  {
    id: 15,
    name: "administratives_organizations",
    display_name: "Organizaciones administrativas",
    route: "/admin/administratives-organizations",
    icon: "IconPoint",
    parent_id: null,
  },
  {
    id: 16,
    name: "reference",
    display_name: "Cátalogos",
    route: "/admin/reference",
    icon: "IconPoint",
    parent_id: null,
  },
  {
    id: 17,
    name: "reference_incidents_roles_permissions",
    display_name: "Permisos de Incidencias",
    route: "/admin/reference/incidents-roles-permissions",
    icon: "IconPoint",
    parent_id: 16,
  },
  {
    id: 18,
    name: "reference_incidents_rules",
    display_name: "Lineamientos de Incidencias",
    route: "/admin/reference/incidents-rules",
    icon: "IconPoint",
    parent_id: 16,
  },
  {
    id: 19,
    name: "reference_salaries",
    display_name: "Salarios",
    route: "/admin/reference/salaries",
    icon: "IconPoint",
    parent_id: 16,
  },
  {
    id: 20,
    name: "reference_requests_roles_permissions",
    display_name: "Permisos de Solicitudes",
    route: "/admin/reference/requests-roles-permissions",
    icon: "IconPoint",
    parent_id: 16,
  },
  {
    id: 21,
    name: "employee_payroll",
    display_name: "Nómina",
    route: "/admin/employees-payroll",
    icon: "IconPoint",
    parent_id: null,
  },
  {
    id: 22,
    name: "reference_catalogs",
    display_name: "Cátalogos del sistema",
    route: "/admin/reference/catalogs",
    icon: "IconPoint",
    parent_id: 16,
  },
  {
    id: 23,
    name: "job_schedule_calendar",
    display_name: "Horarios intercalados",
    route: "/admin/job-schedule-calendar",
    icon: "IconPoint",
    parent_id: null,
  },
];

module.exports = modules;
