const occupation = [
  {
    id: 1,
    cve_code: "01",
    name: "comercio",
    display_name: "Comercio",
  },
  {
    id: 2,
    cve_code: "02",
    name: "conductores",
    display_name: "Conductores",
  },
  {
    id: 3,
    cve_code: "03",
    name: "trabajadores_adminis",
    display_name: "Trabajadores Adminis",
  },
  {
    id: 4,
    cve_code: "04",
    name: "trabajadores_de_la_e",
    display_name: "Trabajadores De La E",
  },
  {
    id: 5,
    cve_code: "05",
    name: "trab_del_arte_espe",
    display_name: "Trab. Del Arte, Espe",
  },
  {
    id: 6,
    cve_code: "06",
    name: "t_de_act_agri_ganad",
    display_name: "T.de Act.agri.ganad.",
  },
  {
    id: 7,
    cve_code: "07",
    name: "t_en_servs_de_prot",
    display_name: "T. En Servs. De Prot",
  },
  {
    id: 8,
    cve_code: "08",
    name: "trabajadores_fabrile",
    display_name: "Trabajadores Fabrile",
  },
  {
    id: 9,
    cve_code: "09",
    name: "tecnicos",
    display_name: "Tecnicos",
  },
  {
    id: 10,
    cve_code: "10",
    name: "profesionista_asalar",
    display_name: "Profesionista Asalar",
  },
  {
    id: 11,
    cve_code: "11",
    name: "profesionista_indepe",
    display_name: "Profesionista Indepe",
  },
  {
    id: 12,
    cve_code: "12",
    name: "funciona_de_inst_O_emp_pub.",
    display_name: "Funciona. De Inst. O Emp.pub.",
  },
  {
    id: 13,
    cve_code: "13",
    name: "dunciona_de_inst_0_emp_priv.",
    display_name: "Funciona. De Inst. O Emp.priv.",
  },
  {
    id: 14,
    cve_code: "14",
    name: "estudiante",
    display_name: "Estudiante",
  },
  {
    id: 15,
    cve_code: "15",
    name: "menor_de_edad",
    display_name: "Menor De Edad",
  },
  {
    id: 16,
    cve_code: "16",
    name: "eclesiastico",
    display_name: "Eclesiastico",
  },
  {
    id: 17,
    cve_code: "17",
    name: "hogar",
    display_name: "Hogar",
  },
  {
    id: 18,
    cve_code: "18",
    name: "jubilados_ensionados",
    display_name: "Jubilados O Pensionados",
  },
  {
    id: 19,
    cve_code: "19",
    name: "desempleado",
    display_name: "Desempleado",
  },
  {
    id: 20,
    cve_code: "20",
    name: "policia_municipal",
    display_name: "Policía Municipal",
  },
];
module.exports = occupation;
