const profession = [
  {
    id: 163,
    display_name: "MAESTRÍA EN DERECHO CONSTITUCIONAL Y AMPARO",
    name: "maestria_en_derecho_constitucional_y_amparo",
  },
  {
    id: 164,
    display_name: "MAESTRÍA EN ADMINISTRACIÓN DE RECURSOS HUMANOS",
    name: "maestria_en_administracion_de_recursos_humanos",
  },
  { id: 165, display_name: "ARQUITECTURA", name: "arquitectura" },
  {
    id: 166,
    display_name: "PROFESORA DE EDUCACIÓN PRIMARIA",
    name: "profesora_de_educacion_primaria",
  },
  { id: 167, display_name: "ENFERMERIA Y OBSTETRICIA", name: "enfermeria_y_obstetricia" },
  {
    id: 168,
    display_name: "ING. ELECTRONICA",
    name: "ing._electronica",
  },
  { id: 171, display_name: "INGENIERO ARQUITECTO", name: "ingeniero_arquitecto" },
  {
    id: 174,
    display_name: "LIC. EN HOTELERÍA",
    name: "lic._en_hoteleria",
  },
  { id: 175, display_name: "CIENCIAS DE LA EDUCACIÓN ", name: "ciencias_de_la_educacion_" },
  {
    id: 176,
    display_name: "MAESTRIA EN PEDAGOGIA",
    name: "maestria_en_pedagogia",
  },
  {
    id: 177,
    display_name: "LIC. EN BIBLIOTECOLOGÍA Y GESTIÓN DE INFORMACIÓN",
    name: "lic._en_bibliotecologia_y_gestion_de_informacion",
  },
  {
    id: 180,
    display_name: "LIC. EN COMERCIO INTERNACIONAL",
    name: "lic._en_comercio_internacional",
  },
  { id: 181, display_name: "MAESTRÍA EN ADMINISTRACIÓN", name: "maestria_en_administracion" },
  {
    id: 182,
    display_name: "ING. EN GESTION EMPRESARIAL",
    name: "ing._en_gestion_empresarial",
  },
  { id: 188, display_name: "LIC. EN DISEÑO GRÁFICO", name: "lic._en_diseno_grafico" },
  {
    id: 189,
    display_name: "LIC. EN ADMINISTRACION TURISTICA",
    name: "lic._en_administracion_turistica",
  },
  { id: 190, display_name: "CONTADOR PRIVADO", name: "contador_privado" },
  {
    id: 191,
    display_name: "LIC. EN GESTION TURISTICA",
    name: "lic._en_gestion_turistica",
  },
  {
    id: 192,
    display_name: "LIC. EN DISEÑO GRAFICO EN MEDIOS DIGITALES",
    name: "lic._en_diseno_grafico_en_medios_digitales",
  },
  { id: 193, display_name: "LIC. EN CONTADURIA", name: "lic._en_contaduria" },
  {
    id: 194,
    display_name: "LIC. EN HOMEOPATIA",
    name: "lic._en_homeopatia",
  },
  { id: 195, display_name: "QUIMICO FARMACOBIOLOGO", name: "quimico_farmacobiologo" },
  {
    id: 196,
    display_name: "LIC. EN QUIMICO FARMACOBIOLOGO",
    name: "lic._en_quimico_farmacobiologo",
  },
  { id: 197, display_name: "ING, MECATRONICA", name: "ing,_mecatronica" },
  {
    id: 199,
    display_name: "LIC. EN EDUCACIÓN FISICA Y DEPORTES",
    name: "lic._en_educacion_fisica_y_deportes",
  },
  { id: 317, display_name: "ADMINISTRACIÓN PUBLICA", name: "administracion_publica" },
  {
    id: 319,
    display_name: "MAESTRIA EN ADMINISTRACIÓN PUBLICA",
    name: "maestria_en_administracion_publica",
  },
  {
    id: 321,
    display_name: "LIC. EN EDUCACIÓN FÍSICA Y DEPORTE",
    name: "lic._en_educacion_fisica_y_deporte",
  },
  { id: 323, display_name: "MEDICO CIRUJANO", name: "medico_cirujano" },
  {
    id: 325,
    display_name: "TEC. EN INFORMATICA Y DISEÑO",
    name: "tec._en_informatica_y_diseno",
  },
  {
    id: 326,
    display_name: "LIC. EN EDUCACIÓN ESPECIAL EN EL AREA INTELECTUAL",
    name: "lic._en_educacion_especial_en_el_area_intelectual",
  },
  {
    id: 327,
    display_name: "LIC. EN POLITICA Y GESTION PUBLICA",
    name: "lic._en_politica_y_gestion_publica",
  },
  { id: 329, display_name: "SECRETARIA EJECUTIVA", name: "secretaria_ejecutiva" },
  {
    id: 330,
    display_name: "TECNICO EN ENFERMERIA",
    name: "tecnico_en_enfermeria",
  },
  { id: 331, display_name: "DOCTORADO EN DERECHO PENAL", name: "doctorado_en_derecho_penal" },
  {
    id: 332,
    display_name: "LIC. EN ALIMENTOS",
    name: "lic._en_alimentos",
  },
  {
    id: 335,
    display_name: "LIC. EN GESTION Y PROMOCION DE LAS ARTES",
    name: "lic._en_gestion_y_promocion_de_las_artes",
  },
  { id: 336, display_name: "LIC. EN DISEÑO INDUSTRIAL", name: "lic._en_diseno_industrial" },
  {
    id: 337,
    display_name: "LIC. EN PERIODISMO Y COMUNICACION COLECTIVA",
    name: "lic._en_periodismo_y_comunicacion_colectiva",
  },
  {
    id: 338,
    display_name: "ING. EN TECNOLOGÍA DE LA INFORMACION",
    name: "ing._en_tecnologia_de_la_informacion",
  },
  {
    id: 340,
    display_name: "ING. AGRONOMO EN PRODUCCIÓN ANIMAL",
    name: "ing._agronomo_en_produccion_animal",
  },
  { id: 343, display_name: "ING. EN BIOTECNOLOGIA", name: "ing._en_biotecnologia" },
  {
    id: 346,
    display_name: "TECNICO EN CONTABILIDAD Y ADMINISTRACIÓN",
    name: "tecnico_en_contabilidad_y_administracion",
  },
  {
    id: 352,
    display_name: "LIC. EN SEGURIDAD PÚBLICA Y PROTECCIÓN CIUDADANA",
    name: "lic._en_seguridad_publica_y_proteccion_ciudadana",
  },
  { id: 353, display_name: "TECNICO EN CONTABILIDAD", name: "tecnico_en_contabilidad" },
  {
    id: 355,
    display_name: "LIC. EN LENGUA Y LITERATURA HISPANOAMERICANA",
    name: "lic._en_lengua_y_literatura_hispanoamericana",
  },
  { id: 357, display_name: "MEDICO", name: "medico" },
  {
    id: 358,
    display_name: "DR. EN DERECHO PÚBLICO",
    name: "dr._en_derecho_publico",
  },
  {
    id: 360,
    display_name: "MTRO. EN DERECHO CONSTITUCIONAL Y AMPARO",
    name: "mtro._en_derecho_constitucional_y_amparo",
  },
  {
    id: 361,
    display_name: "TECNICO BACHILLER EN AUTOTRONICA",
    name: "tecnico_bachiller_en_autotronica",
  },
  {
    id: 366,
    display_name: "MAESTRÍA EN ADMINISTRACIÓN Y POLÍTICAS PÚBLICAS",
    name: "maestria_en_administracion_y_politicas_publicas",
  },
  {
    id: 368,
    display_name: "TEC. EN CONTABILIDAD Y ADMINISTRACION",
    name: "tec._en_contabilidad_y_administracion",
  },
  { id: 369, display_name: "TSU EN PROTECCION CIVIL", name: "tsu_en_proteccion_civil" },
  { id: 372, display_name: "LIC. EN IMAGOLOGIOA", name: "lic._en_imagologioa" },
  {
    id: 373,
    display_name: "TECNICO EN RADIOLOGIA E IMAGEN",
    name: "tecnico_en_radiologia_e_imagen",
  },
  {
    id: 374,
    display_name: "LIC. EN COMERCIO Y NEGOCIOS INTERNACIONALES",
    name: "lic._en_comercio_y_negocios_internacionales",
  },
  {
    id: 378,
    display_name: "MAESTRIA EN DERECHO CON ESPECIALIDAD EN PENAL",
    name: "maestria_en_derecho_con_especialidad_en_penal",
  },
  { id: 379, display_name: "MTRA. EN PEDAGOGIA", name: "mtra._en_pedagogia" },
  {
    id: 380,
    display_name: "LIC. EN DESARROLLO MUNICIPAL Y GOBERNABILIDAD",
    name: "lic._en_desarrollo_municipal_y_gobernabilidad",
  },
  {
    id: 381,
    display_name: "MTRA EN DERECHO CONSTITUCIONAL Y AMPARO",
    name: "mtra_en_derecho_constitucional_y_amparo",
  },
  {
    id: 382,
    display_name: "MAESTRIA EN INGENIERIA ADMINISTRATIVA",
    name: "maestria_en_ingenieria_administrativa",
  },
  {
    id: 383,
    display_name: "MAESTRIA EN CIENCIAS SOCIALES Y HUMANISTICAS",
    name: "maestria_en_ciencias_sociales_y_humanisticas",
  },
  { id: 386, display_name: "TECNICO EN TRABAJO SOCIAL", name: "tecnico_en_trabajo_social" },
  {
    id: 387,
    display_name: "MAESTRIA EN ADMINISTRACION DE TECNOLOGIAS DE LA IN",
    name: "maestria_en_administracion_de_tecnologias_de_la_in",
  },
  {
    id: 389,
    display_name: "INGENIERO INDUSTRIAL EN ELECTRONICA",
    name: "ingeniero_industrial_en_electronica",
  },
  { id: 391, display_name: "LIC. EN BIBLIOTECOLOGIA", name: "lic._en_bibliotecologia" },
  {
    id: 393,
    display_name: "DOCTORADO EN TERRITORIO Y MEDIO AMBIENTE",
    name: "doctorado_en_territorio_y_medio_ambiente",
  },
  {
    id: 394,
    display_name: "MAESTRIA EN ING. DEL MEDIO AMBIENTE",
    name: "maestria_en_ing._del_medio_ambiente",
  },
  {
    id: 395,
    display_name: "LIC. EN MERCADO Y MERCADOS FINANCIEROS",
    name: "lic._en_mercado_y_mercados_financieros",
  },
  {
    id: 398,
    display_name: "MAESTRIA EN TECNOLOGIAS EN INFORMATICA",
    name: "maestria_en_tecnologias_en_informatica",
  },
  {
    id: 399,
    display_name: "MAESTRIA EN DISEÑO DE MEDIOS DIGITALES",
    name: "maestria_en_diseno_de_medios_digitales",
  },
  {
    id: 409,
    display_name: "MAESTRIA EN CIENCIAS PENALES",
    name: "maestria_en_ciencias_penales",
  },
  { id: 411, display_name: "INFORMATICA ADMINISTRATIVA", name: "informatica_administrativa" },
  {
    id: 412,
    display_name: "MAESTRIA EN CIENCIAS DE BIOTECNOLOGIA",
    name: "maestria_en_ciencias_de_biotecnologia",
  },
  {
    id: 414,
    display_name: "LICENCIATURA EN SEGURIDAD PUBLICA Y PROTECCION CIU",
    name: "licenciatura_en_seguridad_publica_y_proteccion_ciu",
  },
  { id: 415, display_name: "MAESTRIA EN ARQUITECTURA", name: "maestria_en_arquitectura" },
  {
    id: 419,
    display_name: "ING. AGRONOMO EN PRODUCCIÓN VEGETAL",
    name: "ing._agronomo_en_produccion_vegetal",
  },
  {
    id: 420,
    display_name: "LIC. EN FINANZAS Y CONTADURIA PÚBLICA",
    name: "lic._en_finanzas_y_contaduria_publica",
  },
  { id: 421, display_name: "LIC. EN IDIOMA FRANCES", name: "lic._en_idioma_frances" },
  {
    id: 423,
    display_name: "LIC. EN ARQUITECTURA",
    name: "lic._en_arquitectura",
  },
  {
    id: 427,
    display_name: "MAESTRIA EN EDUCACIÓN SUPERIOR",
    name: "maestria_en_educacion_superior",
  },
  {
    id: 428,
    display_name: "LIC. EN BANCA Y MERCADOS FINANCIEROS",
    name: "lic._en_banca_y_mercados_financieros",
  },
  {
    id: 429,
    display_name: "MAESTRO EN ARQUITECTURA Y URBANISMO",
    name: "maestro_en_arquitectura_y_urbanismo",
  },
  { id: 430, display_name: "COMPUTACION ADMINISTRATIVA", name: "computacion_administrativa" },
  {
    id: 432,
    display_name: "GINECOLOGIA Y OBSTETRICIA",
    name: "ginecologia_y_obstetricia",
  },
  {
    id: 433,
    display_name: "MAESTRIA EN CIENCIAS PENALES Y DERECHO DE EMPRESA",
    name: "maestria_en_ciencias_penales_y_derecho_de_empresa",
  },
  { id: 436, display_name: "TECNICO EN INFORMATICA", name: "tecnico_en_informatica" },
  {
    id: 437,
    display_name: "MAESTRIA EN GESTION PARA EL DESARROLLO",
    name: "maestria_en_gestion_para_el_desarrollo",
  },
  {
    id: 439,
    display_name: "TENIENTE CORONEL DE ARTILLERIA",
    name: "teniente_coronel_de_artilleria",
  },
  { id: 440, display_name: "LIC. EN NUTRIOLOGIA", name: "lic._en_nutriologia" },
  {
    id: 441,
    display_name: "ING. INDUSTRIAL QUIMICA",
    name: "ing._industrial_quimica",
  },
  { id: 442, display_name: "ING. FORESTAL", name: "ing._forestal" },
  {
    id: 443,
    display_name: "TECNICO PROGRAMADOR ANALISTA EN INFORMATICA",
    name: "tecnico_programador_analista_en_informatica",
  },
  {
    id: 446,
    display_name: "LIC. EN INTERVENCION EDUCATIVA",
    name: "lic._en_intervencion_educativa",
  },
  {
    id: 447,
    display_name: "LIC. EN ADMINISTRACIÓN TURISTICA Y DE LA HOSPITALI",
    name: "lic._en_administracion_turistica_y_de_la_hospitali",
  },
  {
    id: 448,
    display_name: "ING. FORESTAL CON ORIENTACION EN INDUSTRIA",
    name: "ing._forestal_con_orientacion_en_industria",
  },
  {
    id: 449,
    display_name: "LIC. EN ADMINISTRACION DE NEGOCIOS DE LA COMUNICAC",
    name: "lic._en_administracion_de_negocios_de_la_comunicac",
  },
  { id: 450, display_name: "ING. ELECTROMECANICO", name: "ing._electromecanico" },
  {
    id: 451,
    display_name: "LIC. EN MUSICA",
    name: "lic._en_musica",
  },
  { id: 452, display_name: "TSU EN AGROBIOTECNOLOGIA", name: "tsu_en_agrobiotecnologia" },
  {
    id: 453,
    display_name: "MAESTRIA EN DERECHO CIVIL",
    name: "maestria_en_derecho_civil",
  },
  { id: 454, display_name: "JARDINERIA", name: "jardineria" },
  {
    id: 455,
    display_name: "ADMINISTRACION DE INSTITUCIONES EDUCATIVAS",
    name: "administracion_de_instituciones_educativas",
  },
  { id: 457, display_name: "TSU EN ADMINISTRACION", name: "tsu_en_administracion" },
  {
    id: 459,
    display_name: "ING. AGRONOMO TROPICAL",
    name: "ing._agronomo_tropical",
  },
  { id: 460, display_name: "ING. AERONAUTICA", name: "ing._aeronautica" },
  {
    id: 461,
    display_name: "LIC. EN PROTECCIÓN CIVIL",
    name: "lic._en_proteccion_civil",
  },
  {
    id: 462,
    display_name: "LIC. EN DISEÑO Y PRODUCCION PUBLICITARIA",
    name: "lic._en_diseno_y_produccion_publicitaria",
  },
  { id: 463, display_name: "TEC. EN INFORMATICA", name: "tec._en_informatica" },
  {
    id: 466,
    display_name: "MAESTRIA EN FINANZAS CORPORATIVAS",
    name: "maestria_en_finanzas_corporativas",
  },
  {
    id: 467,
    display_name: "TEC. PROF. EN SALUD COMUNITARIA",
    name: "tec._prof._en_salud_comunitaria",
  },
  { id: 469, display_name: "LIC. EN PSICOLOGIA SOCIAL", name: "lic._en_psicologia_social" },
  {
    id: 470,
    display_name: "MAESTRIA EN MERCADOTECNIA Y PUBLICIDAD",
    name: "maestria_en_mercadotecnia_y_publicidad",
  },
  {
    id: 471,
    display_name: "MAESTRIA EN PSICOLOGIA CLINICA Y SALUD",
    name: "maestria_en_psicologia_clinica_y_salud",
  },
  {
    id: 472,
    display_name: "LIC. EN NUTRICION Y CIENCIA DE LOS ALIMENTOS",
    name: "lic._en_nutricion_y_ciencia_de_los_alimentos",
  },
  {
    id: 474,
    display_name: "LIC. EN DIRECCION DE NEGOCIOS TURISTICOS",
    name: "lic._en_direccion_de_negocios_turisticos",
  },
  {
    id: 475,
    display_name: "LIC. EN INVESTIGACION CRIMINAL",
    name: "lic._en_investigacion_criminal",
  },
  {
    id: 479,
    display_name: "TECNICO PROFESIONAL EN ADMINISTRACION",
    name: "tecnico_profesional_en_administracion",
  },
  {
    id: 480,
    display_name: "MAESTRIA EN DESARROLLO URBANO Y ORDENAMIENTO DEL T",
    name: "maestria_en_desarrollo_urbano_y_ordenamiento_del_t",
  },
  {
    id: 481,
    display_name: "MAESTRIA EN VIAS TERRESTRES",
    name: "maestria_en_vias_terrestres",
  },
  {
    id: 482,
    display_name: "MIGRACIONES INTERNACIONALES E INTEGRACION SOCIAL",
    name: "migraciones_internacionales_e_integracion_social",
  },
  { id: 484, display_name: "MAESTRIA EN PUBLICIDAD", name: "maestria_en_publicidad" },
  {
    id: 486,
    display_name: "MAESTRO EN CONTADURIA",
    name: "maestro_en_contaduria",
  },
  {
    id: 487,
    display_name: "ING. EN ENERGIAS RENOVABLES",
    name: "ing._en_energias_renovables",
  },
  { id: 489, display_name: "MAESTRIA EN DERECHO FISCAL", name: "maestria_en_derecho_fiscal" },
  {
    id: 490,
    display_name: "INFORMATICA",
    name: "informatica",
  },
  {
    id: 491,
    display_name: "TECNICO EN INFORMATICA AGROPECUARIA",
    name: "tecnico_en_informatica_agropecuaria",
  },
  {
    id: 492,
    display_name: "MAESTRO EN PROCESO PENAL ACUSATORIO",
    name: "maestro_en_proceso_penal_acusatorio",
  },
  {
    id: 493,
    display_name: "MAESTRIA EN CIENCIAS DE LA COMUNICACION",
    name: "maestria_en_ciencias_de_la_comunicacion",
  },
  { id: 494, display_name: "AUXILIAR DE EDUCADORA", name: "auxiliar_de_educadora" },
  {
    id: 498,
    display_name: "LIC. EN CIENCIAS POLITICAS Y ADMINISTRACION PUBLIC",
    name: "lic._en_ciencias_politicas_y_administracion_public",
  },
  { id: 503, display_name: "MTRO EN DERECHO PENAL", name: "mtro_en_derecho_penal" },
  {
    id: 504,
    display_name: "LIC. EN GASTRONOMIA",
    name: "lic._en_gastronomia",
  },
  {
    id: 505,
    display_name: "LIC, EN CIENCIAS DE LA TIERRA",
    name: "lic,_en_ciencias_de_la_tierra",
  },
  {
    id: 509,
    display_name: "LIC. EN JAZZ Y MUSICA POPULAR",
    name: "lic._en_jazz_y_musica_popular",
  },
  { id: 511, display_name: "SECRETARIA MECANOGRAFA", name: "secretaria_mecanografa" },
  {
    id: 513,
    display_name: "M. EN GESTION INTEGRAL DE RIESGOS Y PROTECCION CIV",
    name: "m._en_gestion_integral_de_riesgos_y_proteccion_civ",
  },
  { id: 515, display_name: "MANTENIMIENTO AUTOMOTRIZ", name: "mantenimiento_automotriz" },
  {
    id: 517,
    display_name: "LIC. EN GESTION DE LA MICRO, PEQUEÑA Y MEDIANA EMP",
    name: "lic._en_gestion_de_la_micro,_pequena_y_mediana_emp",
  },
  {
    id: 519,
    display_name: "LIC. EN CIENCIAS DE LA TIERRA",
    name: "lic._en_ciencias_de_la_tierra",
  },
  { id: 520, display_name: "MAESTRIA EN DERECHO PENAL", name: "maestria_en_derecho_penal" },
  {
    id: 521,
    display_name: "MAESTRÍA EN DERECHO ELECTORAL",
    name: "maestria_en_derecho_electoral",
  },
  {
    id: 525,
    display_name: "MAESTRIA EN INGENIERIA HIDRAULICA AMBIENTAL",
    name: "maestria_en_ingenieria_hidraulica_ambiental",
  },
  { id: 526, display_name: "PREESCOLAR", name: "preescolar" },
  {
    id: 529,
    display_name: "LIC. EN GERONTOLOGIA",
    name: "lic._en_gerontologia",
  },
  {
    id: 530,
    display_name: "TECNICO PROFESIONAL EN MASOTERAPIA",
    name: "tecnico_profesional_en_masoterapia",
  },
  { id: 531, display_name: "DOCTORADO EN DERECHO", name: "doctorado_en_derecho" },
  {
    id: 537,
    display_name: "LIC. EN COMUNICACIÓN E IMAGEN",
    name: "lic._en_comunicacion_e_imagen",
  },
  {
    id: 538,
    display_name: "MAESTRÍA EN DERECHO PROCESAL, CONSTITUCIONAL Y ELE",
    name: "maestria_en_derecho_procesal,_constitucional_y_ele",
  },
  {
    id: 540,
    display_name: "MAESTRIA EN CIENCIAS DE LA EDUCACION",
    name: "maestria_en_ciencias_de_la_educacion",
  },
  {
    id: 542,
    display_name: "TECNICO PROFESIONAL EN COSMETOLOGÍA",
    name: "tecnico_profesional_en_cosmetologia",
  },
  {
    id: 543,
    display_name: "MAESTRIA EN DESARROLLO TURÍSTICO",
    name: "maestria_en_desarrollo_turistico",
  },
  {
    id: 545,
    display_name: "LIC. EN COMUNICACIÓN Y MEDIOS DIGITALES",
    name: "lic._en_comunicacion_y_medios_digitales",
  },
  {
    id: 552,
    display_name: "LIC. EN NUTRICION Y CIENCIAS DE LOS ALIMENTOS",
    name: "lic._en_nutricion_y_ciencias_de_los_alimentos",
  },
  { id: 169, display_name: "GASTRONOMÍA", name: "gastronomia" },
  {
    id: 173,
    display_name: "ADMINISTRACIÓN HOTELERA Y TURÍSTICA",
    name: "administracion_hotelera_y_turistica",
  },
  { id: 187, display_name: "LIC. EN COMUNICACIÓN", name: "lic._en_comunicacion" },
  {
    id: 345,
    display_name: "LIC. EN SEGURIDAD DE POBLACIONES HUMANAS ANTE DESA",
    name: "lic._en_seguridad_de_poblaciones_humanas_ante_desa",
  },
  {
    id: 359,
    display_name: "LIC. EN CRIMINOLOGIA Y CRIMINALISTICA",
    name: "lic._en_criminologia_y_criminalistica",
  },
  { id: 362, display_name: "TSU EN IMAGENOLOGÍA", name: "tsu_en_imagenologia" },
  {
    id: 425,
    display_name: "OFICIAL SUBTENIENTE DE INFANTERIA",
    name: "oficial_subteniente_de_infanteria",
  },
  { id: 445, display_name: "ING. MECANICO AUTOMOTRIZ", name: "ing._mecanico_automotriz" },
  {
    id: 465,
    display_name: "MTRO. EN FINANZAS CORPORATIVAS",
    name: "mtro._en_finanzas_corporativas",
  },
  {
    id: 473,
    display_name: "MAESTRIA EN ING. EN CONSTRUCCION",
    name: "maestria_en_ing._en_construccion",
  },
  {
    id: 477,
    display_name: "TEC. EN SEGURIDAD PUBLICA Y PROTECCION CIUDADANA",
    name: "tec._en_seguridad_publica_y_proteccion_ciudadana",
  },
  { id: 483, display_name: "TECNICO EN AGRONEGOCIOS", name: "tecnico_en_agronegocios" },
  {
    id: 495,
    display_name: "LIC. EN DANZA",
    name: "lic._en_danza",
  },
  {
    id: 497,
    display_name: "DIPLOMADO EN ICONOGRAFIA Y SIMBOLOGIA",
    name: "diplomado_en_iconografia_y_simbologia",
  },
  {
    id: 500,
    display_name: "PROFESIONAL TECNICO EN INFORMATICA",
    name: "profesional_tecnico_en_informatica",
  },
  { id: 506, display_name: "ACTUARIA", name: "actuaria" },
  {
    id: 508,
    display_name: "LIC. EN COMERCIALIZACION",
    name: "lic._en_comercializacion",
  },
  { id: 514, display_name: "MAESTRIA EN DOCENCIA", name: "maestria_en_docencia" },
  {
    id: 516,
    display_name: "LIC. EN EDUCACION DEPORTIVA",
    name: "lic._en_educacion_deportiva",
  },
  {
    id: 524,
    display_name: "ATENCION MEDICA PREHOSPITALARIA",
    name: "atencion_medica_prehospitalaria",
  },
  {
    id: 527,
    display_name: "LIC. EN COMUNICACION INTERCULTURAL",
    name: "lic._en_comunicacion_intercultural",
  },
  { id: 528, display_name: "LIC. EN SEGURIDAD PUBLICA", name: "lic._en_seguridad_publica" },
  {
    id: 532,
    display_name: "LIC. EN DERECHO Y CRIMINOLOGIA",
    name: "lic._en_derecho_y_criminologia",
  },
  { id: 536, display_name: "ING. BIOMEDICO", name: "ing._biomedico" },
  {
    id: 541,
    display_name: "MAESTRIA EN DEFENSA DE LOS DERECHOS HUMANOS",
    name: "maestria_en_defensa_de_los_derechos_humanos",
  },
  {
    id: 547,
    display_name: "MAESTRIA EN DERECHO PENAL Y CRIMINALISTICA",
    name: "maestria_en_derecho_penal_y_criminalistica",
  },
  {
    id: 550,
    display_name: "TECNICO EN REHABILITACION Y MEJORAMIENTO AMBIENTAL",
    name: "tecnico_en_rehabilitacion_y_mejoramiento_ambiental",
  },
  {
    id: 553,
    display_name: "LIC. EN ADMINISTRACION Y VENTAS",
    name: "lic._en_administracion_y_ventas",
  },
  { id: 555, display_name: "TECNICO EN ZOOTECNIA", name: "tecnico_en_zootecnia" },
  {
    id: 556,
    display_name: "TEC. OPERADOR DE MICROCOMPUTADORAS",
    name: "tec._operador_de_microcomputadoras",
  },
  {
    id: 561,
    display_name: "LIC. INGENIERO AGRONOMO ZOOTECNISTA",
    name: "lic._ingeniero_agronomo_zootecnista",
  },
  {
    id: 562,
    display_name: "INGENIERO EN DESARROLLO DE  SOFTWARE",
    name: "ingeniero_en_desarrollo_de_software",
  },
  {
    id: 563,
    display_name: "LIC. EN DISE?O GRAFICO DIGITAL",
    name: "lic._en_dise?o_grafico_digital",
  },
  {
    id: 564,
    display_name: "LIC. EN MERCADOTECNIA Y COMUNICACION GRAFICA",
    name: "lic._en_mercadotecnia_y_comunicacion_grafica",
  },
  {
    id: 566,
    display_name: "MAESTRIA EN GESTION PUBLICA APLICADA",
    name: "maestria_en_gestion_publica_aplicada",
  },
  { id: 567, display_name: "LIC. EN ARTES CULINARIAS", name: "lic._en_artes_culinarias" },
  {
    id: 569,
    display_name: "LIC. EN ADMINISTRACION DE EMPRESAS GLOBALES",
    name: "lic._en_administracion_de_empresas_globales",
  },
  {
    id: 570,
    display_name: "MAESTRO EN CIENCIAS DE LA SALUD",
    name: "maestro_en_ciencias_de_la_salud",
  },
  {
    id: 571,
    display_name: "TECNICO EN MANTENIMIENTO AUTOMOTRIZ",
    name: "tecnico_en_mantenimiento_automotriz",
  },
  {
    id: 572,
    display_name: "MAESTRIA EN ADMINISTRACIÓN DE NEGOCIOS",
    name: "maestria_en_administracion_de_negocios",
  },
  {
    id: 573,
    display_name: "PROFESORA DE EDUCACION PREESCOLAR",
    name: "profesora_de_educacion_preescolar",
  },
  {
    id: 170,
    display_name: "MAESTRÍA EN ADMINISTRACIÓN DE LA CONSTRUCCIÓN",
    name: "maestria_en_administracion_de_la_construccion",
  },
  { id: 200, display_name: "TEC. EN ENFERMERÍA GENERAL", name: "tec._en_enfermeria_general" },
  {
    id: 344,
    display_name: "AGROBIOTECNOLOGIA",
    name: "agrobiotecnologia",
  },
  {
    id: 356,
    display_name: "MTRO EN ADMINISTRACION Y POLITICAS PUBLICAS",
    name: "mtro_en_administracion_y_politicas_publicas",
  },
  { id: 363, display_name: "TRABAJO SOCIAL", name: "trabajo_social" },
  {
    id: 364,
    display_name: "MAESTRO EN ADMINISTRACION",
    name: "maestro_en_administracion",
  },
  {
    id: 476,
    display_name: "ING. EN DESARROLLO DE SOFTWARE",
    name: "ing._en_desarrollo_de_software",
  },
  {
    id: 172,
    display_name: "PROFESOR NORMALISTA EN EDUCACION FISICA",
    name: "profesor_normalista_en_educacion_fisica",
  },
  {
    id: 185,
    display_name: "ING. ELECTRÓNICA EN COMPUTACIÓN",
    name: "ing._electronica_en_computacion",
  },
  { id: 341, display_name: "ENFERMERIA", name: "enfermeria" },
  {
    id: 354,
    display_name: "TECNICO EN ADMINISTRACIÓN DE EMPRESAS",
    name: "tecnico_en_administracion_de_empresas",
  },
  {
    id: 370,
    display_name: "LIC. EN MERCADOTECNIA Y PUBLICIDAD",
    name: "lic._en_mercadotecnia_y_publicidad",
  },
  { id: 385, display_name: "INGENIERO CONSTRUCTOR", name: "ingeniero_constructor" },
  {
    id: 464,
    display_name: "MAESTRIA EN ADMINISTRACION DE EDUCACION SUPERIOR",
    name: "maestria_en_administracion_de_educacion_superior",
  },
  {
    id: 468,
    display_name: "LIC, EN POLITICA Y DESARROLLO SOCIAL",
    name: "lic,_en_politica_y_desarrollo_social",
  },
  {
    id: 496,
    display_name: "MAESTRA EN ESTUDIOS CULTURALES",
    name: "maestra_en_estudios_culturales",
  },
  { id: 507, display_name: "CIENCIAS DE LA TIERRA", name: "ciencias_de_la_tierra" },
  {
    id: 510,
    display_name: "MAESTRIA EN ADM. DE ENERGIA",
    name: "maestria_en_adm._de_energia",
  },
  {
    id: 551,
    display_name: "LIC. EN ENSEÑANZA DEL INGLES",
    name: "lic._en_ensenanza_del_ingles",
  },
  {
    id: 560,
    display_name: "LIC. EN DISEÑO DE LA COMUNICACION GRÁFICA",
    name: "lic._en_diseno_de_la_comunicacion_grafica",
  },
  {
    id: 324,
    display_name: "LIC. EN DESARROLLO HUMANO",
    name: "lic._en_desarrollo_humano",
  },
  {
    id: 342,
    display_name: "MAESTRIA EN DERECHO PROCESAL CIVIL",
    name: "maestria_en_derecho_procesal_civil",
  },
  { id: 349, display_name: "AUXILIAR DE EDUCADORAS", name: "auxiliar_de_educadoras" },
  {
    id: 384,
    display_name: "LIC. EN DERECHOS HUMANOS",
    name: "lic._en_derechos_humanos",
  },
  {
    id: 416,
    display_name: "ING. EN TECNOLOGIA AMBIENTAL",
    name: "ing._en_tecnologia_ambiental",
  },
  { id: 424, display_name: "MAYOR DE INFANTERIA", name: "mayor_de_infanteria" },
  {
    id: 435,
    display_name: "ING. EN GEOMATICA",
    name: "ing._en_geomatica",
  },
  {
    id: 485,
    display_name: "TECNICO EN AIRE ACONDICIONADO Y REFRIGERACION",
    name: "tecnico_en_aire_acondicionado_y_refrigeracion",
  },
  {
    id: 184,
    display_name: "LIC. EN ADMINISTRACIÓN DE EMPRESAS TURISTICAS",
    name: "lic._en_administracion_de_empresas_turisticas",
  },
  { id: 350, display_name: "TSU EN PROTECION CIVIL", name: "tsu_en_protecion_civil" },
  {
    id: 351,
    display_name: "CURSO DE BUSQUEDA Y RESCATE",
    name: "curso_de_busqueda_y_rescate",
  },
  { id: 365, display_name: "MTRA EN PEDAGOGIA", name: "mtra_en_pedagogia" },
  {
    id: 388,
    display_name: "MAESTRIA EN EDUCACION",
    name: "maestria_en_educacion",
  },
  {
    id: 392,
    display_name: "MAESTRIA EN ESTUDIOS POLITICOS Y SOCIALES",
    name: "maestria_en_estudios_politicos_y_sociales",
  },
  {
    id: 396,
    display_name: "MEDICO CIRUJANO GINECOLOGIA Y OBSTETRICIA",
    name: "medico_cirujano_ginecologia_y_obstetricia",
  },
  {
    id: 417,
    display_name: "MTRO. EN ARQUITECTURA Y URBANISMO",
    name: "mtro._en_arquitectura_y_urbanismo",
  },
  { id: 422, display_name: "MAESTRIA EN ALTA DIRECCION", name: "maestria_en_alta_direccion" },
  {
    id: 431,
    display_name: "DR EN FILOSOFIA",
    name: "dr_en_filosofia",
  },
  {
    id: 518,
    display_name: "MAESTRIA EN CIENCIAS DE LA COMPUTACION",
    name: "maestria_en_ciencias_de_la_computacion",
  },
  {
    id: 523,
    display_name: "PROFESIONAL TECNICO EN ENFERMERIA GENERAL",
    name: "profesional_tecnico_en_enfermeria_general",
  },
  {
    id: 533,
    display_name: "ING. EN CIENCIAS AMBIENTALES",
    name: "ing._en_ciencias_ambientales",
  },
  { id: 535, display_name: "LIC. NATUROTERAPIA", name: "lic._naturoterapia" },
  {
    id: 539,
    display_name: "MAESTRIA EN ESTUDIOS URBANOS Y REGIONALES",
    name: "maestria_en_estudios_urbanos_y_regionales",
  },
  { id: 544, display_name: "ING. CONSTRUCTOR", name: "ing._constructor" },
  {
    id: 546,
    display_name: "ESPECIALIDAD EN ENDODONCIA",
    name: "especialidad_en_endodoncia",
  },
  {
    id: 548,
    display_name: "MAESTRIA EN EDUCACION PRIMARIA",
    name: "maestria_en_educacion_primaria",
  },
  {
    id: 549,
    display_name: "LIC. EN ENSEÑANZA Y APRENDIZAJE",
    name: "lic._en_ensenanza_y_aprendizaje",
  },
  { id: 559, display_name: "MAESTRIA EN JUICIOS ORALES", name: "maestria_en_juicios_orales" },
  {
    id: 320,
    display_name: "LIC. EN ADMINISTRACION DE SISTEMAS COMPUTACIONALES",
    name: "lic._en_administracion_de_sistemas_computacionales",
  },
  { id: 322, display_name: "ING. ELECTRICA", name: "ing._electrica" },
  {
    id: 328,
    display_name: "MAESTRIA EN DIRECCIÓN DE GOBIERNO Y POLITICAS PUBL",
    name: "maestria_en_direccion_de_gobierno_y_politicas_publ",
  },
  { id: 367, display_name: "DOCTORADO EN EDUCACION", name: "doctorado_en_educacion" },
  {
    id: 413,
    display_name: "TECNICO EN INFORMATICA ADMINISTRATIVA",
    name: "tecnico_en_informatica_administrativa",
  },
  { id: 426, display_name: "MAESTRIA EN FINANZAS", name: "maestria_en_finanzas" },
  {
    id: 438,
    display_name: "ESPECIALIDAD EN ASISTENTE EN EDUCACION INFANTIL",
    name: "especialidad_en_asistente_en_educacion_infantil",
  },
  {
    id: 499,
    display_name: "ING. TOPOGRAFICA E DHIDROLOGIA",
    name: "ing._topografica_e_dhidrologia",
  },
  {
    id: 565,
    display_name: "LIC. EN EDUCACION MEDIA, ESP. EN CIENCIAS NATURALE",
    name: "lic._en_educacion_media,_esp._en_ciencias_naturale",
  },
  {
    id: 347,
    display_name: "MAESTRO EN ADMINISTRACION PUBLICA",
    name: "maestro_en_administracion_publica",
  },
  {
    id: 377,
    display_name: "ADMINISTRACIÓN PUBLICA, FEDERAL, ESTATAL Y MPAL",
    name: "administracion_publica,_federal,_estatal_y_mpal",
  },
  { id: 400, display_name: "SRIO EN TAQUIMECANOGRAFIA", name: "srio_en_taquimecanografia" },
  {
    id: 407,
    display_name: "LIC. EN MEDICO",
    name: "lic._en_medico",
  },
  {
    id: 408,
    display_name: "MAESTRIA EN CIENCIAS JURIDICO PENALES Y CRIMINOLOG",
    name: "maestria_en_ciencias_juridico_penales_y_criminolog",
  },
  { id: 444, display_name: "ABOGADO NOTARIO Y ACTUARIO", name: "abogado_notario_y_actuario" },
  {
    id: 456,
    display_name: "DERECHO FISCAL",
    name: "derecho_fiscal",
  },
  { id: 458, display_name: "TECNICO EN HISTOPATOLOGIA", name: "tecnico_en_histopatologia" },
  {
    id: 605,
    display_name: "ANTROPOLOGO FISICO",
    name: "antropologo_fisico",
  },
  { id: 606, display_name: "ANTROPOLOGO SOCIAL", name: "antropologo_social" },
  {
    id: 701,
    display_name: "ARQUITECTO",
    name: "arquitecto",
  },
  { id: 604, display_name: "BIOLOGO", name: "biologo" },
  {
    id: 862,
    display_name: "CARDENAL",
    name: "cardenal",
  },
  { id: 406, display_name: "CIRUJANO DENTISTA", name: "cirujano_dentista" },
  {
    id: 502,
    display_name: "CONTADOR PUBLICO",
    name: "contador_publico",
  },
  { id: 501, display_name: "CONTADOR PUBLICO AUDITOR", name: "contador_publico_auditor" },
  {
    id: 603,
    display_name: "ETNOLOGO",
    name: "etnologo",
  },
  { id: 602, display_name: "FISICO", name: "fisico" },
  {
    id: 601,
    display_name: "FISICO MATEMATICO",
    name: "fisico_matematico",
  },
  { id: 870, display_name: "GENERAL", name: "general" },
  {
    id: 101,
    display_name: "ING. ADMINISTRADOR DE SISTEMAS",
    name: "ing._administrador_de_sistemas",
  },
  { id: 103, display_name: "ING. AGRONOMO", name: "ing._agronomo" },
  {
    id: 102,
    display_name: "ING. AGROINDUSTRIAL",
    name: "ing._agroindustrial",
  },
  {
    id: 104,
    display_name: "ING. AGRONOMO ADMINISTRADOR",
    name: "ing._agronomo_administrador",
  },
  { id: 105, display_name: "ING. AGRONOMO FITOTECNISTA", name: "ing._agronomo_fitotecnista" },
  {
    id: 106,
    display_name: "ING. AGRONOMO FRUTICULTOR",
    name: "ing._agronomo_fruticultor",
  },
  { id: 107, display_name: "ING. AGRONOMO HORTICULTOR", name: "ing._agronomo_horticultor" },
  {
    id: 108,
    display_name: "ING. AGRONOMO PARASITOLOGO",
    name: "ing._agronomo_parasitologo",
  },
  { id: 109, display_name: "ING. AGRONOMO ZOOTECNISTA", name: "ing._agronomo_zootecnista" },
  {
    id: 110,
    display_name: "ING. BIOMEDICA",
    name: "ing._biomedica",
  },
  { id: 111, display_name: "ING. BIOQUIMICO", name: "ing._bioquimico" },
  {
    id: 112,
    display_name: "ING. BIOQUIMICO EN ALIMENTOS MARINOS",
    name: "ing._bioquimico_en_alimentos_marinos",
  },
  { id: 113, display_name: "ING. CIVIL", name: "ing._civil" },
  {
    id: 114,
    display_name: "ING. COMPUTACION ADMTVA Y DE PRODUCCION",
    name: "ing._computacion_admtva_y_de_produccion",
  },
  { id: 115, display_name: "ING. ELECTRICISTA", name: "ing._electricista" },
  {
    id: 116,
    display_name: "ING. ELECTRICO ADMINISTRATIVO",
    name: "ing._electrico_administrativo",
  },
  {
    id: 117,
    display_name: "ING. ELECTRONICA Y COMUNICACIONES",
    name: "ing._electronica_y_comunicaciones",
  },
  { id: 118, display_name: "ING. EN ARQUITECTURA", name: "ing._en_arquitectura" },
  {
    id: 119,
    display_name: "ING. EN AUTOMATIZACION Y CONTROL",
    name: "ing._en_automatizacion_y_control",
  },
  {
    id: 120,
    display_name: "ING. EN CIBERNETICA Y C D E LA COMUNICACION",
    name: "ing._en_cibernetica_y_c_d_e_la_comunicacion",
  },
  {
    id: 121,
    display_name: "ING. EN CIENCIAS COMPUTACIONALES",
    name: "ing._en_ciencias_computacionales",
  },
  { id: 122, display_name: "ING. EN COMPUTACION", name: "ing._en_computacion" },
  {
    id: 123,
    display_name: "ING. EN COMUNICACIONES",
    name: "ing._en_comunicaciones",
  },
  {
    id: 124,
    display_name: "ING. EN CONTROL Y COMPUTACION",
    name: "ing._en_control_y_computacion",
  },
  { id: 125, display_name: "ING. EN ELECTRONICA", name: "ing._en_electronica" },
  {
    id: 126,
    display_name: "ING. EN INDUSTRIA ALIMENTARIA",
    name: "ing._en_industria_alimentaria",
  },
  { id: 127, display_name: "ING. EN PLANEACION", name: "ing._en_planeacion" },
  {
    id: 128,
    display_name: "ING. EN PLANIFICACION Y DISE?O",
    name: "ing._en_planificacion_y_dise?o",
  },
  { id: 129, display_name: "ING. EN PRODUCCION", name: "ing._en_produccion" },
  {
    id: 130,
    display_name: "ING. EN SISTEMAS",
    name: "ing._en_sistemas",
  },
  {
    id: 131,
    display_name: "ING. EN SISTEMAS COMPUTACIONALES",
    name: "ing._en_sistemas_computacionales",
  },
  {
    id: 132,
    display_name: "ING. EN SISTEMAS ELECTRONICOS",
    name: "ing._en_sistemas_electronicos",
  },
  { id: 133, display_name: "ING. INDUSTRIAL", name: "ing._industrial" },
  {
    id: 134,
    display_name: "ING. INDUSTRIAL ADMINISTRADOR",
    name: "ing._industrial_administrador",
  },
  {
    id: 135,
    display_name: "ING. INDUSTRIAL EN PRODUCCION",
    name: "ing._industrial_en_produccion",
  },
  {
    id: 136,
    display_name: "ING. INDUSTRIAL Y DE SISTEMAS",
    name: "ing._industrial_y_de_sistemas",
  },
  {
    id: 137,
    display_name: "ING. INDUSTRIAL Y ELECTRONICA",
    name: "ing._industrial_y_electronica",
  },
  { id: 138, display_name: "ING. MECANICO", name: "ing._mecanico" },
  {
    id: 139,
    display_name: "ING. MECANICO ADMINISTRADOR",
    name: "ing._mecanico_administrador",
  },
  { id: 140, display_name: "ING. MECANICO ELECTRICISTA", name: "ing._mecanico_electricista" },
  {
    id: 141,
    display_name: "ING. MECANICO ELECTRICO",
    name: "ing._mecanico_electrico",
  },
  { id: 142, display_name: "ING. METALURGICO", name: "ing._metalurgico" },
  {
    id: 143,
    display_name: "ING. QUIMICO",
    name: "ing._quimico",
  },
  { id: 144, display_name: "ING. QUIMICO ADMINISTRADOR", name: "ing._quimico_administrador" },
  {
    id: 145,
    display_name: "ING. QUIMICO BACTERIOLOGO PARASITOLOGO",
    name: "ing._quimico_bacteriologo_parasitologo",
  },
  { id: 146, display_name: "ING. QUIMICO BIOLOGO", name: "ing._quimico_biologo" },
  {
    id: 147,
    display_name: "ING. QUIMICO DE PROCESO",
    name: "ing._quimico_de_proceso",
  },
  {
    id: 148,
    display_name: "ING. QUIMICO FARMACO-BIOLOGO",
    name: "ing._quimico_farmaco-biologo",
  },
  { id: 149, display_name: "ING. QUIMICO INDUSTRIAL", name: "ing._quimico_industrial" },
  {
    id: 150,
    display_name: "ING. QUIMICO Y DE SISTEMAS",
    name: "ing._quimico_y_de_sistemas",
  },
  { id: 151, display_name: "ING. ZOOTECNISTA", name: "ing._zootecnista" },
  {
    id: 152,
    display_name: "INGENIERIA EN SISTEMAS DE INFORMACION",
    name: "ingenieria_en_sistemas_de_informacion",
  },
  { id: 153, display_name: "INGENIERO ELECTRONICO", name: "ingeniero_electronico" },
  {
    id: 154,
    display_name: "INGENIERO EN ACUSTICA",
    name: "ingeniero_en_acustica",
  },
  { id: 155, display_name: "INGENIERO EN INFORMATICA", name: "ingeniero_en_informatica" },
  {
    id: 874,
    display_name: "INGLES TECNICO INDUSTRIAL",
    name: "ingles_tecnico_industrial",
  },
  {
    id: 607,
    display_name: "INSTRUCTOR DE LENGUA INGLESA",
    name: "instructor_de_lengua_inglesa",
  },
  {
    id: 202,
    display_name: "LIC. ADMINISTRACION BANCARIA",
    name: "lic._administracion_bancaria",
  },
  {
    id: 203,
    display_name: "LIC. ADMINISTRACION EMPRESAS TURISTICAS",
    name: "lic._administracion_empresas_turisticas",
  },
  {
    id: 204,
    display_name: "LIC. ADMINISTRACION INDUSTRIAL",
    name: "lic._administracion_industrial",
  },
  {
    id: 205,
    display_name: "LIC. CIENCIAS ECONOMICAS Y EMPRESARIALES",
    name: "lic._ciencias_economicas_y_empresariales",
  },
  {
    id: 206,
    display_name: "LIC. COMERCIO INTERNACIONAL",
    name: "lic._comercio_internacional",
  },
  { id: 207, display_name: "LIC. COMUNICACION SOCIAL", name: "lic._comunicacion_social" },
  {
    id: 208,
    display_name: "LIC. EN ACTUARIA",
    name: "lic._en_actuaria",
  },
  { id: 209, display_name: "LIC. EN ADMINISTRACION", name: "lic._en_administracion" },
  {
    id: 210,
    display_name: "LIC. EN ADMINISTRACION AGROPECUARIA",
    name: "lic._en_administracion_agropecuaria",
  },
  {
    id: 211,
    display_name: "LIC. EN ADMINISTRACION DE EMPRESAS",
    name: "lic._en_administracion_de_empresas",
  },
  {
    id: 212,
    display_name: "LIC. EN ADMINISTRACION DE NEGOCIOS",
    name: "lic._en_administracion_de_negocios",
  },
  {
    id: 213,
    display_name: "LIC. EN ADMINISTRACION DE PERSONAL",
    name: "lic._en_administracion_de_personal",
  },
  {
    id: 214,
    display_name: "LIC. EN ADMINISTRACION DE REC HUMANOS",
    name: "lic._en_administracion_de_rec_humanos",
  },
  {
    id: 215,
    display_name: "LIC. EN ADMINISTRACION DEL TIE",
    name: "lic._en_administracion_del_tie",
  },
  {
    id: 216,
    display_name: "LIC. EN ADMINISTRACION EDUCATIVA",
    name: "lic._en_administracion_educativa",
  },
  {
    id: 217,
    display_name: "LIC. EN ADMINISTRACION FINANCIERA",
    name: "lic._en_administracion_financiera",
  },
  {
    id: 218,
    display_name: "LIC. EN ADMINISTRACION PROFESIONAL",
    name: "lic._en_administracion_profesional",
  },
  {
    id: 219,
    display_name: "LIC. EN ADMINISTRACION PUBLICA",
    name: "lic._en_administracion_publica",
  },
  {
    id: 220,
    display_name: "LIC. EN ADMINISTRACION Y FINANZAS",
    name: "lic._en_administracion_y_finanzas",
  },
  {
    id: 221,
    display_name: "LIC. EN ADMON PUBLICA Y CIENCIAS POLITICAS",
    name: "lic._en_admon_publica_y_ciencias_politicas",
  },
  {
    id: 222,
    display_name: "LIC. EN ADMON Y GESTION DE ORGANIZACIONES",
    name: "lic._en_admon_y_gestion_de_organizaciones",
  },
  { id: 223, display_name: "LIC. EN AGRONEGOCIOS", name: "lic._en_agronegocios" },
  {
    id: 224,
    display_name: "LIC. EN ARTES VISUALES",
    name: "lic._en_artes_visuales",
  },
  {
    id: 225,
    display_name: "LIC. EN ASUNTOS INTERNACIONALES",
    name: "lic._en_asuntos_internacionales",
  },
  { id: 226, display_name: "LIC. EN BANCA Y FINANZAS", name: "lic._en_banca_y_finanzas" },
  {
    id: 228,
    display_name: "LIC. EN CIENCIAS ADMINISTRATIVAS",
    name: "lic._en_ciencias_administrativas",
  },
  {
    id: 229,
    display_name: "LIC. EN CIENCIAS BIOLOGICAS",
    name: "lic._en_ciencias_biologicas",
  },
  {
    id: 230,
    display_name: "LIC. EN CIENCIAS COMPUTACIONALES",
    name: "lic._en_ciencias_computacionales",
  },
  {
    id: 231,
    display_name: "LIC. EN CIENCIAS DE LA EDUCACION",
    name: "lic._en_ciencias_de_la_educacion",
  },
  {
    id: 232,
    display_name: "LIC. EN CIENCIAS DE LA COMUNICACI?N",
    name: "lic._en_ciencias_de_la_comunicaci?n",
  },
  {
    id: 227,
    display_name: "LIC. EN CIENCIAS DE LA COMUNICACI?N Y PERIODISMO",
    name: "lic._en_ciencias_de_la_comunicaci?n_y_periodismo",
  },
  {
    id: 233,
    display_name: "LIC. EN CIENCIAS DE LA COMUNIDAD",
    name: "lic._en_ciencias_de_la_comunidad",
  },
  {
    id: 234,
    display_name: "LIC. EN CIENCIAS DE LA INFORMATICA",
    name: "lic._en_ciencias_de_la_informatica",
  },
  { id: 235, display_name: "LIC. EN CIENCIAS JURIDICAS", name: "lic._en_ciencias_juridicas" },
  {
    id: 236,
    display_name: "LIC. EN CIENCIAS MARITIMAS",
    name: "lic._en_ciencias_maritimas",
  },
  { id: 237, display_name: "LIC. EN CIENCIAS NATURALES", name: "lic._en_ciencias_naturales" },
  {
    id: 238,
    display_name: "LIC. EN CIENCIAS POLITICAS",
    name: "lic._en_ciencias_politicas",
  },
  { id: 239, display_name: "LIC. EN CIENCIAS QUIMICAS", name: "lic._en_ciencias_quimicas" },
  {
    id: 240,
    display_name: "LIC. EN CIENCIAS SOCIALES",
    name: "lic._en_ciencias_sociales",
  },
  {
    id: 241,
    display_name: "LIC. EN CIENCIAS Y HUMANIDADES",
    name: "lic._en_ciencias_y_humanidades",
  },
  { id: 242, display_name: "LIC. EN COMERCIO EXTERIOR", name: "lic._en_comercio_exterior" },
  {
    id: 243,
    display_name: "LIC. EN COMPUTACION ADMINISTRATIVA",
    name: "lic._en_computacion_administrativa",
  },
  {
    id: 244,
    display_name: "LIC. EN COMUNICACI?N GRAFICA",
    name: "lic._en_comunicaci?n_grafica",
  },
  {
    id: 245,
    display_name: "LIC. EN COMUNICACI?N Y DESARROLLO ORG.",
    name: "lic._en_comunicaci?n_y_desarrollo_org.",
  },
  {
    id: 201,
    display_name: "LIC. EN COMUNICACIONES Y RELACIONES PUBLICAS",
    name: "lic._en_comunicaciones_y_relaciones_publicas",
  },
  { id: 246, display_name: "LIC. EN CONTABILIDAD", name: "lic._en_contabilidad" },
  {
    id: 247,
    display_name: "LIC. EN CONTADURIA PUBLICA",
    name: "lic._en_contaduria_publica",
  },
  {
    id: 248,
    display_name: "LIC. EN CONTADURIA PUBLICA Y AUDITORIA",
    name: "lic._en_contaduria_publica_y_auditoria",
  },
  {
    id: 249,
    display_name: "LIC. EN CONTADURIA PUBLICA Y FINANZAS",
    name: "lic._en_contaduria_publica_y_finanzas",
  },
  { id: 250, display_name: "LIC. EN CRIMINOLOGIA", name: "lic._en_criminologia" },
  {
    id: 251,
    display_name: "LIC. EN DEPORTES",
    name: "lic._en_deportes",
  },
  { id: 252, display_name: "LIC. EN DERECHO", name: "lic._en_derecho" },
  {
    id: 253,
    display_name: "LIC. EN DERECHO PENAL",
    name: "lic._en_derecho_penal",
  },
  {
    id: 254,
    display_name: "LIC. EN DERECHO Y CIENCIAS JURIDICAS",
    name: "lic._en_derecho_y_ciencias_juridicas",
  },
  {
    id: 255,
    display_name: "LIC. EN DERECHO Y CIENCIAS SOCIALES",
    name: "lic._en_derecho_y_ciencias_sociales",
  },
  { id: 256, display_name: "LIC. EN DIBUJO GRAFICO", name: "lic._en_dibujo_grafico" },
  {
    id: 257,
    display_name: "LIC. EN DISE?O DE INTERIORES",
    name: "lic._en_dise?o_de_interiores",
  },
  { id: 258, display_name: "LIC. EN DISE?O DE MODAS", name: "lic._en_dise?o_de_modas" },
  {
    id: 259,
    display_name: "LIC. EN DISE?O GRAFICO",
    name: "lic._en_dise?o_grafico",
  },
  { id: 260, display_name: "LIC. EN DISE?O INDUSTRIAL", name: "lic._en_dise?o_industrial" },
  {
    id: 261,
    display_name: "LIC. EN ECONOMIA",
    name: "lic._en_economia",
  },
  {
    id: 262,
    display_name: "LIC. EN ECONOMIA INTERNACIONAL",
    name: "lic._en_economia_internacional",
  },
  { id: 263, display_name: "LIC. EN EDUCACION", name: "lic._en_educacion" },
  {
    id: 264,
    display_name: "LIC. EN EDUCACION ESPECIAL",
    name: "lic._en_educacion_especial",
  },
  { id: 265, display_name: "LIC. EN EDUCACION MEDIA", name: "lic._en_educacion_media" },
  {
    id: 266,
    display_name: "LIC. EN EDUCACION PREESCOLAR",
    name: "lic._en_educacion_preescolar",
  },
  {
    id: 267,
    display_name: "LIC. EN ELECTRONICA Y SISTEMAS DIGITALES",
    name: "lic._en_electronica_y_sistemas_digitales",
  },
  {
    id: 268,
    display_name: "LIC. EN ESTUDIOS INTERNACIONALES",
    name: "lic._en_estudios_internacionales",
  },
  { id: 269, display_name: "LIC. EN FILOSOFIA", name: "lic._en_filosofia" },
  {
    id: 270,
    display_name: "LIC. EN FILOSOFIA Y TEOLOGIA",
    name: "lic._en_filosofia_y_teologia",
  },
  { id: 271, display_name: "LIC. EN FINANZAS", name: "lic._en_finanzas" },
  {
    id: 272,
    display_name: "LIC. EN FINANZAS INTERNACIONALES",
    name: "lic._en_finanzas_internacionales",
  },
  { id: 273, display_name: "LIC. EN HISTORIA", name: "lic._en_historia" },
  {
    id: 274,
    display_name: "LIC. EN HOTELERIA Y TURISMO",
    name: "lic._en_hoteleria_y_turismo",
  },
  { id: 275, display_name: "LIC. EN IDIOMAS", name: "lic._en_idiomas" },
  {
    id: 276,
    display_name: "LIC. EN INFORMATICA",
    name: "lic._en_informatica",
  },
  {
    id: 277,
    display_name: "LIC. EN INFORMATICA ADMINISTRATIVA",
    name: "lic._en_informatica_administrativa",
  },
  {
    id: 278,
    display_name: "LIC. EN INGENIERIA FINANCIERA",
    name: "lic._en_ingenieria_financiera",
  },
  {
    id: 279,
    display_name: "LIC. EN INGENIERIA Y ARQUITECTURA",
    name: "lic._en_ingenieria_y_arquitectura",
  },
  { id: 280, display_name: "LIC. EN LETRAS ESPA?OLAS", name: "lic._en_letras_espa?olas" },
  {
    id: 281,
    display_name: "LIC. EN LETRAS INGLESAS",
    name: "lic._en_letras_inglesas",
  },
  {
    id: 282,
    display_name: "LIC. EN LINGšÖSTICA APLICADA",
    name: "lic._en_lingsostica_aplicada",
  },
  { id: 283, display_name: "LIC. EN MATEMATICAS", name: "lic._en_matematicas" },
  {
    id: 284,
    display_name: "LIC. EN MERCADOTECNIA",
    name: "lic._en_mercadotecnia",
  },
  {
    id: 309,
    display_name: "LIC. EN NEGOCIOS INTERNACIONALES",
    name: "lic._en_negocios_internacionales",
  },
  { id: 285, display_name: "LIC. EN NUTRICION", name: "lic._en_nutricion" },
  {
    id: 310,
    display_name: "LIC. EN ODONTOLOGIA",
    name: "lic._en_odontologia",
  },
  {
    id: 286,
    display_name: "LIC. EN ORGANIZACI?N DEPORTIVA",
    name: "lic._en_organizaci?n_deportiva",
  },
  { id: 287, display_name: "LIC. EN PEDAGOGIA", name: "lic._en_pedagogia" },
  {
    id: 288,
    display_name: "LIC. EN PERIODISMO",
    name: "lic._en_periodismo",
  },
  {
    id: 289,
    display_name: "LIC. EN PERIODISMO Y COMUNICACI?N COLECTIVA",
    name: "lic._en_periodismo_y_comunicaci?n_colectiva",
  },
  { id: 290, display_name: "LIC. EN PSICOLOGIA", name: "lic._en_psicologia" },
  {
    id: 291,
    display_name: "LIC. EN PSICOLOGIA CLINICA",
    name: "lic._en_psicologia_clinica",
  },
  {
    id: 292,
    display_name: "LIC. EN PSICOLOGIA INDUSTRIAL",
    name: "lic._en_psicologia_industrial",
  },
  { id: 293, display_name: "LIC. EN PSICOLOGIA LABORAL", name: "lic._en_psicologia_laboral" },
  {
    id: 294,
    display_name: "LIC. EN PUBLICIDAD",
    name: "lic._en_publicidad",
  },
  { id: 295, display_name: "LIC. EN RECURSOS HUMANOS", name: "lic._en_recursos_humanos" },
  {
    id: 296,
    display_name: "LIC. EN RELACIONES COMERCIALES",
    name: "lic._en_relaciones_comerciales",
  },
  {
    id: 298,
    display_name: "LIC. EN RELACIONES INDUSTRIALES",
    name: "lic._en_relaciones_industriales",
  },
  {
    id: 299,
    display_name: "LIC. EN RELACIONES INTERNACIONALES",
    name: "lic._en_relaciones_internacionales",
  },
  {
    id: 301,
    display_name: "LIC. EN RELACIONES PUBLICAS",
    name: "lic._en_relaciones_publicas",
  },
  {
    id: 300,
    display_name: "LIC. EN RELACIONES PUBLICAS Y COMUNICACI?N ORG",
    name: "lic._en_relaciones_publicas_y_comunicaci?n_org",
  },
  { id: 297, display_name: "LIC. EN RELACIONS HUMANAS", name: "lic._en_relacions_humanas" },
  {
    id: 302,
    display_name: "LIC. EN SISTEMAS",
    name: "lic._en_sistemas",
  },
  {
    id: 303,
    display_name: "LIC. EN SISTEMAS COMPUTACIONALES",
    name: "lic._en_sistemas_computacionales",
  },
  {
    id: 304,
    display_name: "LIC. EN SISTEMAS DE COMPUTACION ADMINISTRATIVA",
    name: "lic._en_sistemas_de_computacion_administrativa",
  },
  { id: 305, display_name: "LIC. EN SOCIOLOGIA", name: "lic._en_sociologia" },
  {
    id: 306,
    display_name: "LIC. EN TRABAJO SOCIAL",
    name: "lic._en_trabajo_social",
  },
  { id: 307, display_name: "LIC. EN TURISMO", name: "lic._en_turismo" },
  {
    id: 308,
    display_name: "LIC. EN ZOOTECNIA",
    name: "lic._en_zootecnia",
  },
  { id: 312, display_name: "LICENCIADO EN DERECHO", name: "licenciado_en_derecho" },
  {
    id: 313,
    display_name: "LICENCIADO EN DISE?O PUBLICITARIO",
    name: "licenciado_en_dise?o_publicitario",
  },
  { id: 314, display_name: "LICENCIADO EN ECONOMIA", name: "licenciado_en_economia" },
  {
    id: 801,
    display_name: "MAESTRO EDUCACION PRIMARIA",
    name: "maestro_educacion_primaria",
  },
  { id: 802, display_name: "MAESTRO NORMALISTA", name: "maestro_normalista" },
  {
    id: 401,
    display_name: "MEDICO GENERAL",
    name: "medico_general",
  },
  {
    id: 402,
    display_name: "MEDICO HOMEOPATA CIRUJANO PARTERO",
    name: "medico_homeopata_cirujano_partero",
  },
  { id: 403, display_name: "MEDICO ODONTOLOGO", name: "medico_odontologo" },
  {
    id: 404,
    display_name: "MEDICO VETERINARIO",
    name: "medico_veterinario",
  },
  {
    id: 405,
    display_name: "MEDICO VETERINARIO ZOOTECNISTA",
    name: "medico_veterinario_zootecnista",
  },
  { id: 804, display_name: "NORMAL DE EDUCACION FISICA", name: "normal_de_educacion_fisica" },
  {
    id: 803,
    display_name: "NORMAL BASICA",
    name: "normal_basica",
  },
  { id: 861, display_name: "OBISPO", name: "obispo" },
  {
    id: 860,
    display_name: "PRESBITERO",
    name: "presbitero",
  },
  {
    id: 805,
    display_name: "PROFR DE EDUCACION PREESCOLAR",
    name: "profr_de_educacion_preescolar",
  },
  { id: 850, display_name: "SEÑOR", name: "senor" },
  {
    id: 851,
    display_name: "SEÑORA",
    name: "senora",
  },
  { id: 852, display_name: "SEÑORITA", name: "senorita" },
  {
    id: 871,
    display_name: "TENIENTE",
    name: "teniente",
  },
  { id: 156, display_name: "INGENIERO", name: "ingeniero" },
  {
    id: 315,
    display_name: "LICENCIADO",
    name: "licenciado",
  },
  { id: 410, display_name: "DOCTOR (A)", name: "doctor_(a)" },
  {
    id: 810,
    display_name: "PROFESOR",
    name: "profesor",
  },
  { id: 100, display_name: "SIN PROFESION", name: "sin_profesion" },
  {
    id: 157,
    display_name: "INGENIERO EN GESTION EMPRESARIAL",
    name: "ingeniero_en_gestion_empresarial",
  },
  {
    id: 872,
    display_name: "ING. ZOOTECNISTA ADMINISTRADOR",
    name: "ing._zootecnista_administrador",
  },
  { id: 873, display_name: "LIC. EN EDUCACION FISICA", name: "lic._en_educacion_fisica" },
  {
    id: 316,
    display_name: "LICENCIATURA EN ALIMENTOS",
    name: "licenciatura_en_alimentos",
  },
  { id: 158, display_name: "MAESTRIA EN ADMON. PUBLICA", name: "maestria_en_admon._publica" },
  {
    id: 159,
    display_name: "ING. EN MECATRONICA",
    name: "ing._en_mecatronica",
  },
  { id: 160, display_name: "ING. DE SOFTWARE", name: "ing._de_software" },
  {
    id: 161,
    display_name: "ING. AMBIENTAL",
    name: "ing._ambiental",
  },
  { id: 179, display_name: "LIC. EN BIOLOGÍA", name: "lic._en_biologia" },
  {
    id: 198,
    display_name: "LIC. EN ENFERMERIA",
    name: "lic._en_enfermeria",
  },
  { id: 333, display_name: "ING. EN INFORMATICA", name: "ing._en_informatica" },
  {
    id: 334,
    display_name: "LIC. EN EDUCACION PRIMARIA",
    name: "lic._en_educacion_primaria",
  },
  {
    id: 390,
    display_name: "MAESTRIA EN ESTUDIOS CULTURALES",
    name: "maestria_en_estudios_culturales",
  },
  { id: 397, display_name: "MAESTRIA EN VALUACION", name: "maestria_en_valuacion" },
  {
    id: 418,
    display_name: "PROF TEC EN COMBUSTION INTERNA AUTOMOTRIZ",
    name: "prof_tec_en_combustion_interna_automotriz",
  },
  {
    id: 434,
    display_name: "ING. TOPOGRAFO Y FOTOGRAMETRISTA",
    name: "ing._topografo_y_fotogrametrista",
  },
  {
    id: 478,
    display_name: "MAESTRIA EN DIDACTICA DE LA EDUCACION FISICA",
    name: "maestria_en_didactica_de_la_educacion_fisica",
  },
  {
    id: 488,
    display_name: "LIC. EN PSICOLOGIA EDUCATIVA",
    name: "lic._en_psicologia_educativa",
  },
  { id: 512, display_name: "LIC. EN TERAPIA FISICA", name: "lic._en_terapia_fisica" },
  {
    id: 522,
    display_name: "LIC. EN ENSEÑANZA Y APRENDIZAJE DE LA FISICA EN ED",
    name: "lic._en_ensenanza_y_aprendizaje_de_la_fisica_en_ed",
  },
  {
    id: 534,
    display_name: "MAESTRIA EN DERECHO LABORAL",
    name: "maestria_en_derecho_laboral",
  },
  {
    id: 554,
    display_name: "LIC. EN INGENIERIA EN DESARROLLO Y TECNOLOGIAS DE ",
    name: "lic._en_ingenieria_en_desarrollo_y_tecnologias_de_",
  },
  {
    id: 557,
    display_name: "LIC. EN ANTROPOLOGIA HISTORÍCA",
    name: "lic._en_antropologia_historica",
  },
  {
    id: 568,
    display_name: "LIC. EN GESTION Y DESARROLLO TURISTICO",
    name: "lic._en_gestion_y_desarrollo_turistico",
  },
  {
    id: 558,
    display_name: "TECNICO EN SEGURIDAD PUBLICA Y PROTECCION CIUDADAN",
    name: "tecnico_en_seguridad_publica_y_proteccion_ciudadan",
  },
];

module.exports = profession;
