const requestStatus = [
  {
    id: 1,
    name: "creada",
    display_name: "CREADA",
    description: "El empleado o el enlace crea la solicitud",
    btn_display_name: "Creada",
    btn_icon: "clock",
    btn_color: "warning",
    type: 1,
    active: true,
    allowed_roles_to_update: "1,2,3,4,5,6,7",
    permission_name: "",
  },
  {
    id: 2,
    name: "aprobada",
    display_name: "APROBADA",
    description: "El capturista aprueba la solicitud",
    btn_display_name: "Aprobada",
    btn_icon: "check",
    btn_color: "success",
    type: 1,
    active: true,
    allowed_roles_to_update: "1,5,6,7",
    permission_name: "can_approve",
  },
  {
    id: 3,
    name: "rechazada",
    display_name: "RECHAZADA",
    description: "El capturista rechaza la solicitud",
    btn_display_name: "Rechazada",
    btn_icon: "x",
    btn_color: "error",
    type: 1,
    active: true,
    allowed_roles_to_update: "1,5,6,7",
    permission_name: "can_reject",
  },
  {
    id: 4,
    name: "eliminada",
    display_name: "ELIMINADA",
    description: "El capturista elimina la solicitud",
    btn_display_name: "Eliminada",
    btn_icon: "trash",
    btn_color: "warning",
    type: 1,
    active: true,
    allowed_roles_to_update: "1,2,3",
    permission_name: "can_delete",
  },
  {
    id: 5,
    name: "cancelada",
    display_name: "CANCELADA",
    description: "El empleado o el enlace cancela la solicitud",
    btn_display_name: "Cancelada",
    btn_icon: "x",
    btn_color: "error",
    type: 1,
    active: true,
    allowed_roles_to_update: "1,2,3",
    permission_name: "can_cancel",
  },
];
module.exports = requestStatus;
