const state = [
  {
    id: 1,
    country_id: 1,
    name: "aguascalientes",
    display_name: "Aguascalientes",
  },
  {
    id: 2,
    country_id: 1,
    name: "baja_california",
    display_name: "Baja California",
  },
  {
    id: 3,
    country_id: 1,
    name: "baja_california_sur",
    display_name: "Baja California Sur",
  },
  {
    id: 4,
    country_id: 1,
    name: "campeche",
    display_name: "Campeche",
  },
  {
    id: 5,
    country_id: 1,
    name: "coahuila_de_zaragoza",
    display_name: "Coahuila de Zaragoza",
  },
  {
    id: 6,
    country_id: 1,
    name: "colima",
    display_name: "Colima",
  },
  {
    id: 7,
    country_id: 1,
    name: "chiapas",
    display_name: "Chiapas",
  },
  {
    id: 8,
    country_id: 1,
    name: "chihuahua",
    display_name: "Chihuahua",
  },
  {
    id: 9,
    country_id: 1,
    name: "distrito_federal",
    display_name: "Distrito Federal",
  },
  {
    id: 10,
    country_id: 1,
    name: "durango",
    display_name: "Durango",
  },
  {
    id: 11,
    country_id: 1,
    name: "guanajuato",
    display_name: "Guanajuato",
  },
  {
    id: 12,
    country_id: 1,
    name: "guerrero",
    display_name: "Guerrero",
  },
  {
    id: 13,
    country_id: 1,
    name: "hidalgo",
    display_name: "Hidalgo",
  },
  {
    id: 14,
    country_id: 1,
    name: "jalisco",
    display_name: "Jalisco",
  },
  {
    id: 15,
    country_id: 1,
    name: "mexico",
    display_name: "México",
  },
  {
    id: 16,
    country_id: 1,
    name: "michoacan_de_ocampo",
    display_name: "Michoacán de Ocampo",
  },
  {
    id: 17,
    country_id: 1,
    name: "morelos",
    display_name: "Morelos",
  },
  {
    id: 18,
    country_id: 1,
    name: "nayarit",
    display_name: "Nayarit",
  },
  {
    id: 19,
    country_id: 1,
    name: "nuevo_leon",
    display_name: "Nuevo León",
  },
  {
    id: 20,
    country_id: 1,
    name: "oaxaca_de_juarez",
    display_name: "Oaxaca de Juárez",
  },
  {
    id: 21,
    country_id: 1,
    name: "puebla",
    display_name: "Puebla",
  },
  {
    id: 22,
    country_id: 1,
    name: "queretaro",
    display_name: "Querétaro",
  },
  {
    id: 23,
    country_id: 1,
    name: "quintana_roo",
    display_name: "Quintana Roo",
  },
  {
    id: 24,
    country_id: 1,
    name: "san_luis_potosi",
    display_name: "San Luis Potosí",
  },
  {
    id: 25,
    country_id: 1,
    name: "sinaloa",
    display_name: "Sinaloa",
  },
  {
    id: 26,
    country_id: 1,
    name: "sonora",
    display_name: "Sonora",
  },
  {
    id: 27,
    country_id: 1,
    name: "tabasco",
    display_name: "Tabasco",
  },
  {
    id: 28,
    country_id: 1,
    name: "tamaulipas",
    display_name: "Tamaulipas",
  },
  {
    id: 29,
    country_id: 1,
    name: "tlaxcala",
    display_name: "Tlaxcala",
  },
  {
    id: 30,
    country_id: 1,
    name: "veracruz_de_ignacio_de_la_llave",
    display_name: "Veracruz de Ignacio de la Llave",
  },
  {
    id: 31,
    country_id: 1,
    name: "yucatan",
    display_name: "Yucatán",
  },
  {
    id: 32,
    country_id: 1,
    name: "zacatecas",
    display_name: "Zacatecas",
  },
];

module.exports = state;
