export const request = {
  pageNotnumber: {
    page: "a",
    limit: 1,
    search: "a",
    request_id: 1,
    request_status_id: 1,
    created_at: "2025-01-01",
  },
  pageZero: {
    page: 0,
    limit: 1,
    search: "a",
    request_id: 1,
    request_status_id: 1,
    created_at: "2025-01-01",
  },
  pageNegative: {
    page: -1,
    limit: 1,
    search: "a",
    request_id: 1,
    request_status_id: 1,
    created_at: "2025-01-01",
  },
  limitNotnumber: {
    page: 1,
    limit: "a",
    search: "a",
    request_id: 1,
    request_status_id: 1,
    created_at: "2025-01-01",
  },
  limitZero: {
    page: 1,
    limit: 0,
    search: "a",
    request_id: 1,
    request_status_id: 1,
    created_at: "2025-01-01",
  },
  limitNegative: {
    page: 1,
    limit: -1,
    search: "a",
    request_id: 1,
    request_status_id: 1,
    created_at: "2025-01-01",
  },
  requestIdNotNumber: {
    page: 1,
    limit: 5,
    search: "a",
    request_id: "a",
    request_status_id: 1,
    created_at: "2025-01-01",
  },
  requestStatusIdNotNumber: {
    page: 1,
    limit: 5,
    search: "a",
    request_id: 1,
    request_status_id: "a",
    created_at: "2025-01-01",
  },
  requestIdZero: {
    page: 1,
    limit: 5,
    search: "a",
    request_id: 0,
    request_status_id: 1,
    created_at: "2025-01-01",
  },
  requestStatusIdZero: {
    page: 1,
    limit: 5,
    search: "a",
    request_id: 1,
    request_status_id: 0,
    created_at: "2025-01-01",
  },
  requestIdNegative: {
    page: 1,
    limit: 5,
    search: "a",
    request_id: -1,
    request_status_id: 1,
    created_at: "2025-01-01",
  },
  requestStatusIdNegative: {
    page: 1,
    limit: 5,
    search: "a",
    request_id: 1,
    request_status_id: -1,
    created_at: "2025-01-01",
  },
  invalidCreatedAt: {
    page: 1,
    limit: 5,
    search: "a",
    request_id: 1,
    request_status_id: 1,
    created_at: "texto",
  },
  longSearch: {
    page: 1,
    limit: 5,
    search: "a".repeat(256),
    request_id: 1,
    request_status_id: 1,
    created_at: "2025-01-01",
  },
  validData: {
    page: 1,
    limit: 5,
    search: "agui",
    request_id: 1,
    request_status_id: 1,
    created_at: "2025-01-01",
  },
};
