import { generator } from "./generator";

export const request = {
  validData: generator.request(),
  direccionIdNotNumber: generator.request({ direccionId: "a" as unknown as number }),
  direccionIdZero: generator.request({ direccionId: 0 }),
  direccionIdNegative: generator.request({ direccionId: -1 }),
  direccionIdLong: generator.request({ direccionId: Number("9".repeat(16)) }),
  directorNotNumber: generator.request({ director: "a" as unknown as number }),
  directorZero: generator.request({ director: 0 }),
  directorNegative: generator.request({ director: -1 }),
  directorLong: generator.request({ director: Number("9".repeat(16)) }),
  secretaryNotNumber: generator.request({ secretary: "a" as unknown as number }),
  secretaryZero: generator.request({ secretary: 0 }),
  secretaryNegative: generator.request({ secretary: -1 }),
  secretaryLong: generator.request({ secretary: Number("9".repeat(16)) }),
  coordinatorNotNumber: generator.request({ coordinator: "a" as unknown as number }),
  coordinatorZero: generator.request({ coordinator: 0 }),
  coordinatorNegative: generator.request({ coordinator: -1 }),
  coordinatorLong: generator.request({ coordinator: Number("9".repeat(16)) }),
  immediateResponsibleNotNumber: generator.request({ immediateResponsible: "a" as unknown as number }),
  immediateResponsibleZero: generator.request({ immediateResponsible: 0 }),
  immediateResponsibleNegative: generator.request({ immediateResponsible: -1 }),
  immediateResponsibleLong: generator.request({ immediateResponsible: Number("9".repeat(16)) }),
  emptyStartDate: generator.request({ startDate: "" }),
  emptyEndDate: generator.request({ endDate: "" }),
};
