import { generator } from "./generator";

export const request = {
  validData: generator.request({
    "name": "Enrique",
    "paternalLastName": "Guillén",
    "maternalLastName": "Álvarez",
    "birthday": "1991-12-14",
    "rfc": "GUAR911214EF5",
    "curp": "GUAR911214HCSLLF08",
    "genderId": 2,
    "addressLine1": "Av mango",
    "addressLine2": "218",
    "addressLine3": "18",
    "addressLine4": "Chiapas solidario",
    "postalCode": "29018",
    "postalCodeSat": "29018",
    "stateId": 7,
    "municipalityId": 81,
    "startJobDate": "2025-01-01",
    "endJobDate": "2025-06-30",
    "categoryId": 15,
    "tradeUnionId": 1,
    "secretariaId": 1,
    "direccionId": 1,
    "id": 1,
    "numberEmployee": "106449",
    "userId": 186,
    "statusEmployeeId": 2,
    "directorId": null,
    "sustituteId": null,
    "maritalStatusId": 2,
    "schoolingId": 1,
    "professionId": 2,
    "occupationId": 2,
    "identificationTypeId": 1,
    "identificationFolio": "INE00018UYGTHN210931",
    "employeeId": 66,
    "employeeTypeId": 1,
    "salary": "0",
    "direccionSecretariaId": 1,
    "municipalityStateId": 7,
    "countryId": 1,
    "employeeTypeName": "base_no_sindicalizado",
  }),
  emptyNumberEmployee: generator.request({ numberEmployee: "" }),
  emptyName: generator.request({ name: "" }),
  emptyPaternalLastName: generator.request({ paternalLastName: "" }),
  emptyMaternalLastName: generator.request({ maternalLastName: "" }),
  emptyBirthday: generator.request({ birthday: "" }),
  longNumberEmployee: generator.request({ numberEmployee: "123456789012345678901" }),
  longName: generator.request({ name: "NombreExcesivamenteLargoParaValidacionNombreExcesivamenteLargoParaValidacionNombreExcesivamenteLargoParaValidacionNombreExcesivamenteLargoParaValidacionNombreExcesivamenteLargoParaValidacionNombreExcesivamenteLargoParaValidacionNombreExcesivamenteLargoPara" }),
  longPaternalLastName: generator.request({ paternalLastName: "ApellidoExcesivamenteLargo" }),
  longMaternalLastName: generator.request({ maternalLastName: "ApellidoExcesivamenteLargo" }),
  duplicatedRfcCurp: generator.request({ rfc: "DUPLICATED", curp: "DUPLICATED" }),
  emptyAddressLine1: generator.request({ addressLine1: "" }),
  emptyPostalCode: generator.request({ postalCode: "" }),
  emptyMunicipalityId: generator.request({ municipalityId: "0" }),
  emptyCategoryId: generator.request({ categoryId: "0" }),
  emptyEmployeeTypeName: generator.request({ employeeTypeName: "" }),
};
