export enum IncidentTypes {
  INCAPACIDAD = "incapacidad",
  JUSTIFICACION_ENTRADA = "justificacion_entrada",
  JUSTIFICACION_SALIDA = "justificacion_salida",
  JUSTIFICACION_ENTRADA_SALIDA = "justificacion_entrada_salida",
  LACTANCIA = "lactancia",
  PATERNIDAD = "paternidad",
  PERMISO_ESPECIAL = "permiso_especial",
  PERMISO_SIN_GOCE = "permiso_sin_goce",
  PERMISO_ECONOMICO = "permiso_economico",
  VACACIONES = "vacaciones",
  COMISION = "comision",
  RETARDO = "retardo",
  LICENCIA_FALLECIMIENTO = "licencia_fallecimiento",
  LICENCIA_MEDICA = "licencia_medica",
  RETARDO_MAYOR = "retardo_mayor",
  SUSPENSION = "suspension",
  ARRESTO = "arresto",
  PERMISO_ECONOMICO_CUMPLEANOS = "permiso_economico_cumpleanos",
}

export const INCIDENT_TYPES_ID = {
  INCAPACIDAD: 1,
  JUSTIFICACION_ENTRADA: 2,
  JUSTIFICACION_SALIDA: 3,
  JUSTIFICACION_ENTRADA_SALIDA: 4,
  LACTANCIA: 5,
  PATERNIDAD: 6,
  PERMISO_ESPECIAL: 7,
  PERMISO_ECONOMICO: 8,
  PERMISO_SIN_GOCE: 9,
  VACACIONES: 10,
  COMISION: 11,
  RETARDO: 12,
  FALTA: 13,
  LICENCIA_MEDICA: 14,
  RETARDO_MAYOR: 15,
  SUSPENSION: 16,
  ARRESTO: 17,
  PERMISO_ECONOMICO_CUMPLEANOS: 18,
};
