export const SYSTEM_LOG_ACTIONS = {
  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",
  ACTIVATE_USER: "ACTIVATE_USER",
  DEACTIVATE_USER: "DEACTIVATE_USER",
} as const;

export type SystemLogAction = (typeof SYSTEM_LOG_ACTIONS)[keyof typeof SYSTEM_LOG_ACTIONS];
